"""Machine 3: the halting branch is v_3(a) = 1 -- CLOSED FORM, all j.

sieve_m3.py finds by exact discrete logarithm that every branch (j, r) with
j <= 20 except (1,1) and (1,2) is forbidden.  This file proves it for ALL j, by
a gap argument, and machine-checks every step of the proof.

SETUP.  N = 3^{j+1} + 1, and the sieve condition is  27^k = P (mod N)  with
P = r*3^j - 3^{j+1}(j + c_r), c_1 = 3, c_2 = 4.

STEP 1.  3^{j+1} = -1 (mod N), so P = r*3^j + j + c_r (mod N).

STEP 2.  The multiplicative group generated by 3 modulo N is
             <3> = {3^i : 0 <= i <= j}  u  {N - 3^i : 0 <= i <= j},
         exactly 2(j+1) residues, because 3^{j+1} = -1 makes 3 have order
         2(j+1).  Every power of 27 is a power of 3, so 27^k in <3> always.
         Hence it is enough to show P mod N is NOT in <3>.

STEP 3 (the gap).  Listed in increasing order the elements of <3> are
             1, 3, 9, ..., 3^j,  then  N - 3^j = 2*3^j + 1,  N - 3^{j-1}, ...
         so <3> has a LARGE GAP: no element lies strictly between 3^j and
         2*3^j + 1.  The next gap up is between 2*3^j + 1 and
         N - 3^{j-1} = 2*3^j + 2*3^{j-1} + 1.

STEP 4 (P lands in a gap).  For j >= 2:
    r = 1:  P = 3^j + j + 3,  and  3^j < 3^j + j + 3 < 2*3^j + 1
            because j + 2 < 3^j.                        -> in the first gap.
    r = 2:  P = 2*3^j + j + 4, and 2*3^j + 1 < P < 2*3^j + 2*3^{j-1} + 1
            because j + 3 < 2*3^{j-1}.                  -> in the second gap.
    j = 0:  N = 4, <3> = {1, 3}, P = 0 (r=1) or 2 (r=2): both even, and every
            power of 27 is odd.                         -> excluded.
    j = 1:  N = 10, <3> = {1, 3, 7, 9}, P = 7 (r=1) or 1 (r=2): both ARE in
            <3>, and <27> = <7> = {1,7,9,3} = <3> mod 10, so both are hit.
                                                        -> the only survivors.

THEOREM (machine 3's halting branch).  Machine 3 can halt only out of a step
whose branch has v_3(a) = 1.  Unconditional, all scales, all times, any start.
"""
import sys

sys.path.insert(0, "/Users/tomzahavy/Documents/Claude/collatz/machine3")
sys.path.insert(0, "/Users/tomzahavy/Documents/Claude/collatz/automatic")
sys.path.insert(0, "/Users/tomzahavy/Documents/Claude/collatz/baker")
from sieve_m3 import affine, cr                            # noqa: E402

JMAX = int(sys.argv[1]) if len(sys.argv) > 1 else 400


def group3(j):
    """<3> modulo N = 3^{j+1}+1, computed directly (no theory used)."""
    N = 3 ** (j + 1) + 1
    g, x = set(), 1
    while x not in g:
        g.add(x)
        x = x * 3 % N
    return g, N


print(f"machine 3: proving the halting branch is v_3 = 1, for j <= {JMAX}\n")

print("STEP 1+2  the claimed description of <3> mod N, checked directly")
for j in list(range(0, 12)) + [40, 80]:
    g, N = group3(j)
    claim = {3 ** i % N for i in range(j + 1)} | {(N - 3 ** i) % N
                                                 for i in range(j + 1)}
    assert g == claim, (j, sorted(g)[:8], sorted(claim)[:8])
    assert len(g) == 2 * (j + 1) or j == 0, (j, len(g))
    assert pow(3, j + 1, N) == N - 1
print("  <3> = {3^i} u {N-3^i}, i <= j, of size 2(j+1), and 3^{j+1} = -1: OK "
      "(j <= 11, 40, 80)")

print("\nSTEP 3  the gap: no element of <3> lies in (3^j, 2*3^j+1)")
for j in range(1, 14):
    g, N = group3(j)
    assert not any(3 ** j < e < 2 * 3 ** j + 1 for e in g), j
    assert not any(2 * 3 ** j + 1 < e < 2 * 3 ** j + 2 * 3 ** (j - 1) + 1
                   for e in g), j
print("  both gaps verified elementwise for 1 <= j <= 13: OK")

print("\nSTEP 4  P reduces as claimed and lands strictly inside a gap")
for j in range(0, JMAX + 1):
    N = 3 ** (j + 1) + 1
    for r in (1, 2):
        _, _, P, _ = affine(j, r)
        assert P % N == (r * 3 ** j + j + cr(r)) % N, (j, r)
        if j >= 2:
            p = r * 3 ** j + j + cr(r)
            assert p < N, (j, r)                    # no reduction needed
            if r == 1:
                assert 3 ** j < p < 2 * 3 ** j + 1, (j, r)
                assert j + 2 < 3 ** j
            else:
                assert 2 * 3 ** j + 1 < p < 2 * 3 ** j + 2 * 3 ** (j - 1) + 1
                assert j + 3 < 2 * 3 ** (j - 1)
print(f"  P = r*3^j + j + c_r (mod N) and lies strictly inside a gap of <3>, "
      f"for every 2 <= j <= {JMAX}: OK")

print("\nCROSS-CHECK  brute-force membership test, no gap argument used")
bad = []
for j in range(0, 60):
    g, N = group3(j)
    for r in (1, 2):
        _, _, P, _ = affine(j, r)
        inside = P % N in g
        if inside != (j == 1):
            bad.append((j, r, inside))
print(f"  'P mod N in <3>' agrees with 'j == 1' for every j <= 59, r in "
      f"{{1,2}}: {'OK' if not bad else f'MISMATCH {bad}'}")

print("\nTHEOREM (proved, machine-checked): machine 3 halts only out of a step "
      "with v_3(a) = 1.")
print("  frequency of such steps: P(v_3 = 1) = (2/3)(1/3) = 2/9 = 0.2222")
print("  => 7/9 = 77.78% of all steps are unconditionally excluded, and the "
      "surviving\n     set is a SINGLE valuation rather than a residual tail.")
