"""Build the WS3 report: forbidden valuations, and where the ladder stops."""
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                TableStyle, HRFlowable)
from reportlab.lib.colors import HexColor

OUT = "/Users/tomzahavy/Documents/Claude/collatz/baker/ws3_report.pdf"

styles = getSampleStyleSheet()
H1 = ParagraphStyle("H1x", parent=styles["Heading1"], spaceBefore=15, spaceAfter=7,
                    fontSize=13.5)
BODY = ParagraphStyle("Bodyx", parent=styles["Normal"], fontSize=10.5, leading=14.5,
                      spaceAfter=7)
MATHC = ParagraphStyle("MathCx", parent=styles["Normal"], fontName="Times-Italic",
                       fontSize=10.5, leading=15, alignment=TA_CENTER,
                       spaceBefore=4, spaceAfter=8)
CELL = ParagraphStyle("Cellx", parent=styles["Normal"], fontName="Times-Roman",
                      fontSize=9.5, leading=12.5)
CODE = ParagraphStyle("Codex", parent=styles["Normal"], fontName="Courier",
                      fontSize=8.8, leading=11.5, spaceAfter=7,
                      textColor=HexColor("#333333"))
TITLE = ParagraphStyle("Titlex", parent=styles["Title"], fontSize=17, leading=21,
                       spaceAfter=4)
SUB = ParagraphStyle("Subx", parent=styles["Normal"], alignment=TA_CENTER,
                     textColor=HexColor("#555555"), fontSize=10.5, spaceAfter=16)
BLUE = HexColor("#1a3c6e")


def P(t, s=BODY):
    return Paragraph(t, s)


def tab(rows, header, widths):
    data = [[P(f"<b>{h}</b>", CELL) for h in header]]
    data += [[P(c, CELL) for c in r] for r in rows]
    t = Table(data, colWidths=list(widths), repeatRows=1)
    t.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.4, HexColor("#b8c4d6")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 5), ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("BACKGROUND", (0, 0), (-1, 0), HexColor("#e8eef7")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
         [colors.white, HexColor("#f6f8fb")])]))
    return t


story = []
story.append(P("Forbidden valuations: where a halt cannot be", TITLE))
story.append(P("WS3, first execution &mdash; an unconditional infinite-time "
               "exclusion, and the point where the ladder stops climbing "
               "&mdash; July 26, 2026", SUB))
story.append(HRFlowable(width="100%", thickness=1, color=BLUE, spaceAfter=12))

story.append(P("1. Result", H1))
story.append(P(
    "On the branch v<sub>2</sub>(x) = v the Needle map is affine with fixed "
    "point x* = 2<super>v</super>(3 &minus; 2v)/3, so a run of n consecutive "
    "steps of valuation v satisfies 2<super>(v+1)n</super>(3x<sub>n</sub> "
    "&minus; 2<super>v</super>(3&minus;2v)) = q<sub>v</sub><super>n</super>"
    "(3x<sub>0</sub> &minus; 2<super>v</super>(3&minus;2v)) with "
    "q<sub>v</sub> = 2<super>v+1</super> + 3. If that run ends in a halt, "
    "x<sub>n</sub> = 2<super>m</super>, and because q<sub>v</sub> is odd:"))
story.append(P("q<sub>v</sub><super>n</super>&nbsp; divides &nbsp;"
               "3&middot;2<super>m&minus;v</super> &minus; 3 + 2v"
               "&nbsp;&nbsp;&nbsp;&nbsp;(*)", MATHC))
story.append(P(
    "For v = 0 this is 5<super>n</super> | 2<super>m</super> &minus; 1, the "
    "LTE case already on file (m &ge; 4&middot;5<super>n&minus;1</super>). For "
    "general v it is a discrete-logarithm condition, and the new point is that "
    "<b>it is often unsolvable</b>: 3<super>&minus;1</super>(3&minus;2v) need "
    "not lie in the subgroup generated by 2 modulo q<sub>v</sub>."))
story.append(P(
    "<b>Theorem (forbidden valuations).</b> If (*) is unsolvable modulo "
    "q<sub>v</sub>, then no orbit of the Space Needle can halt at a step "
    "whose predecessor has valuation v &mdash; at any scale, at any time. "
    "Among v &le; 34 that excludes"))
story.append(P("v = 1, 4, 7, 9, 10, 12, 13, 18, 19, 21, 22, 23, 24, 25, 26, "
               "28, 31, 32, 33&nbsp;&nbsp;(19 of 35)", MATHC))
story.append(P(
    "and since valuation v has frequency 2<super>&minus;(v+1)</super>, this "
    "removes an asymptotic <b>28.7%</b> of all steps as possible "
    "halt-predecessors. Measured on the actual orbit over its first 200,000 "
    "steps: <b>28.91%</b> of steps are unconditionally proved not to be "
    "followed by a halt. Independent confirmation: brute force over "
    "x &lt; 3,000,000 finds single-step halting seeds only at valuations "
    "{0, 2, 3, 6} &mdash; every one allowed, none forbidden."))

story.append(P("2. The position bound, and why it adds almost nothing", H1))
story.append(P(
    "For an allowed v, (*) still pins the halting exponent to one residue "
    "class modulo ord(2, q<sub>v</sub><super>n</super>), so m &ge; "
    "t<sub>min</sub>(v,n) + v. The map expands by at most 3 per step, so "
    "x<sub>N</sub> &le; 6&middot;3<super>N</super> and m &le; 1.585N + 2.6; a "
    "halt at the end of a v-run of length n therefore cannot occur before "
    "step N<sub>min</sub> = (t<sub>min</sub>(v,n) + v &minus; 2.6)/1.585:"))
story.append(tab([
    ("1", "&mdash;", "4.1", "5.9", "12", "6.6", "60"),
    ("2", "&mdash;", "48", "108", "2.4e3", "1.5e3", "1.1e4"),
    ("3", "&mdash;", "742", "2.1e3", "5.5e4", "1.4e6", "2.1e6"),
], ("run length n", "v=0", "v=2", "v=3", "v=5", "v=6", "v=8"),
    (1.0 * inch, 0.75 * inch, 0.75 * inch, 0.8 * inch, 0.9 * inch,
     0.9 * inch, 0.9 * inch)))
story.append(P(
    "The numbers grow fast in n &mdash; t<sub>min</sub> scales like "
    "q<sub>v</sub><super>n&minus;1</super> &mdash; but they are racing against "
    "m, which grows only <i>linearly</i> in the step index. On the real orbit "
    "the position bound excludes <b>8 steps out of 200,000</b>. Essentially "
    "all of the 28.91% comes from the forbidden valuations alone."))
story.append(P(
    "<b>That is the honest verdict on this rung of the ladder: it saturates "
    "immediately.</b> The exclusion is permanent and unconditional, but it is "
    "a fixed 28.7% of steps and it does not improve with more computation, "
    "because runs long enough for the position bound to bite are "
    "exponentially rare exactly where the bound would need them to be common."))

story.append(P("3. Why the multi-block rungs need Baker, and what changes", H1))
story.append(P(
    "The plan proposed grading halting branch words by block count B and "
    "climbing the Steiner &rarr; Simons&ndash;de Weger &rarr; Hercher ladder. "
    "Working the algebra out shows why B = 1 behaves so differently from "
    "B &ge; 2. Condition (*) constrains m using only the <i>last</i> block, "
    "because the fixed point x* does not depend on where the run started. "
    "Earlier blocks do not chain into further divisibility conditions on m; "
    "they constrain the value entering the configuration instead. So the "
    "congruence method has exactly one rung, and it has now been climbed."))
story.append(P(
    "Blocks beyond the last enter only through an inequality. Composing runs "
    "of valuations v<sub>1</sub>, &hellip;, v<sub>B</sub> and lengths "
    "n<sub>1</sub>, &hellip;, n<sub>B</sub> and demanding the result be "
    "2<super>m</super> gives a small linear form in logarithms,"))
story.append(P("| m log2 &minus; &Sigma;<sub>i</sub> n<sub>i</sub> "
               "log(q<sub>vi</sub> / 2<super>vi+1</super>) &minus; log C | "
               "&nbsp;small,", MATHC))
story.append(P(
    "which is Baker territory proper: Matveev for the lower bound, "
    "continued-fraction or LLL reduction to bring the resulting exponent "
    "bound down to a finite check. That is a substantially larger piece of "
    "work than this one, and the honest expectation from the B = 1 experience "
    "is that it constrains <i>which</i> exponent combinations are possible "
    "rather than excluding whole valuations &mdash; useful, but a different "
    "shape of result. The one encouraging precedent remains April 2026&rsquo;s "
    "BB(6) machine settled by Baker&ndash;W&uuml;stholz."))

story.append(P("4. Verification ledger", H1))
story.append(tab([
    ("The run closed form and (*)",
     "PROVED (affine conjugation to the fixed point; q<sub>v</sub> odd). "
     "Machine-verified at n = 1 on random values for v = 0..3, and every "
     "single-step halting seed below 3,000,000 satisfies (*)."),
    ("Forbidden valuations for v &le; 34",
     "MACHINE-VERIFIED by exact discrete logarithm (baby-step giant-step) "
     "modulo q<sub>v</sub>. Unsolvable mod q<sub>v</sub> implies unsolvable "
     "mod q<sub>v</sub><super>n</super> for all n, so the exclusion holds for "
     "runs of every length."),
    ("28.91% of the first 200,000 orbit steps excluded",
     "MACHINE-VERIFIED (direct simulation), and consistent with the "
     "asymptotic 0.2868 predicted by the valuation frequencies."),
    ("The position bound table",
     "MACHINE-VERIFIED. Conservative: run lengths are capped at n = 3 when "
     "computing t<sub>min</sub>, which imposes fewer constraints and so can "
     "only understate the exclusion."),
    ("Non-halting", "OPEN. This constrains where a halt can be, not whether "
     "one exists; 71% of steps remain unexcluded by this method."),
], ("claim", "status"), (1.9 * inch, 4.4 * inch)))
story.append(Spacer(1, 8))
story.append(P("Code: runs.py (algebra, (*), discrete logs, tests), "
               "ladder.py (forbidden set, position bounds, orbit exclusion).",
               CODE))

doc = SimpleDocTemplate(OUT, pagesize=letter, leftMargin=0.85 * inch,
                        rightMargin=0.85 * inch, topMargin=0.8 * inch,
                        bottomMargin=0.8 * inch,
                        title="WS3: forbidden valuations for the Space Needle")
doc.build(story)
print(f"wrote {OUT}")
