"""WS4.1 -- the size frontier: one syntax for cryptids and for universality.

SYNTAX.  A one-counter guarded affine machine (GAM) is a triple (sigma, R, q):
the state is an integer x > 0; a selector sigma(x) picks a rule index; rule i
rewrites x -> (a_i x + b_i)/c_i, its guard being that the division is exact.
Two selector kinds occur in this project:

    RES(d)   sigma(x) = the first i whose guard divides x   -- decided by
             x mod d, d = lcm of the guards.  FINITELY many affine pieces.
    VAL(q)   sigma(x) = v_q(x).                                INFINITELY many
             affine pieces, generated by one schema (see branch_type.py).

FRACTRAN is exactly RES with a_i/c_i = p_i/q_i and b_i = 0, so Conway's
universality theorem is a statement about this syntax and needs no translation.

WHAT THIS FILE ESTABLISHES.

  (1) A COMPILER, register machine -> RES-GAM, and a step-exactness check
      against a direct register-machine interpreter.  An I-instruction machine
      compiles to at most 2I rules.  Together with Minsky's theorem that
      register machines are Turing-complete, RES-GAMs are Turing-complete and
      the frontier is at most 2I rules for the smallest universal I.

  (2) A concrete anchor that needs no citation at all: Conway's PRIMEGAME, a
      14-rule RES-GAM, run here and checked to emit exactly the primes.  So
      unbounded nontrivial computation is already available at 14 rules.

  (3) The honest reading of the gap.  Our cryptids are 1-counter machines with
      ONE parametric rule schema.  That is smaller than 14 rules as WRITTEN --
      but VAL(q) supplies an infinite family of affine pieces from that one
      schema, and nothing here proves a 1-schema VAL machine is weaker than a
      14-rule RES machine.  The frontier is an UPPER bound on where universality
      begins; it is not a proof that our machines sit below it in power.

Run: python3 gam.py
"""
from math import gcd
from fractions import Fraction

HALT = "HALT"

# --------------------------------------------------------------- the RES-GAM


class ResGAM:
    """x -> (p_i/q_i) x for the first i with q_i | x; halt if there is none."""

    def __init__(self, fractions, name=""):
        self.fr = [Fraction(p, q) for p, q in fractions]
        self.name = name

    def modulus(self):
        d = 1
        for f in self.fr:
            d = d * f.denominator // gcd(d, f.denominator)
        return d

    def step(self, x):
        for f in self.fr:
            if x % f.denominator == 0:
                return x * f.numerator // f.denominator
        return HALT

    def run(self, x, cap):
        for _ in range(cap):
            y = self.step(x)
            if y is HALT:
                return x, True
            x = y
        return x, False


# ------------------------------------------------- register machine + compiler
# Instructions, labels 0..I-1; falling off the end (label I) halts.
#   ("inc", j, k)      r_j += 1 ; goto k
#   ("dec", j, k, z)   if r_j > 0: r_j -= 1 ; goto k   else: goto z


def rm_step(prog, regs, pc):
    if pc >= len(prog):
        return None
    ins = prog[pc]
    regs = list(regs)
    if ins[0] == "inc":
        _, j, k = ins
        regs[j] += 1
        return regs, k
    _, j, k, z = ins
    if regs[j] > 0:
        regs[j] -= 1
        return regs, k
    return regs, z


PRIMES = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61,
          67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137]


def compile_rm(prog, nregs):
    """Register machine -> RES-GAM.  Returns (gam, encode).

    Registers use primes P[0..nregs-1]; labels 0..I use the next I+1 primes.
    The encoding is  n = prod P[j]^r_j * S[pc], one label prime to the first
    power, so at most one instruction's guards can ever match.
    """
    I = len(prog)
    P = PRIMES[:nregs]
    S = PRIMES[nregs:nregs + I + 1]
    fr = []
    for pc, ins in enumerate(prog):
        if ins[0] == "inc":
            _, j, k = ins
            fr.append((P[j] * S[k], S[pc]))
        else:
            _, j, k, z = ins
            fr.append((S[k], P[j] * S[pc]))        # nonzero branch first
            fr.append((S[z], S[pc]))               # zero branch
    # label I (halt) has no rule, so the GAM halts exactly there.

    def encode(regs, pc):
        n = S[pc]
        for j, r in enumerate(regs):
            n *= P[j] ** r
        return n

    return ResGAM(fr, name=f"compiled({I} instr, {nregs} reg)"), encode


def check_step_exact(prog, nregs, starts, expect, cap=20000):
    """One register-machine step = one GAM step, on the nose, for every start.

    `expect(regs0)` gives the intended value of r0 at halt, so a test program
    that silently loops or computes the wrong thing cannot pass by vacuity.
    """
    gam, enc = compile_rm(prog, nregs)
    bad = steps = wrong = 0
    for regs0 in starts:
        regs, pc, n = list(regs0), 0, enc(list(regs0), 0)
        halted = False
        for _ in range(cap):
            nxt = rm_step(prog, regs, pc)
            g = gam.step(n)
            if nxt is None:                         # register machine halted
                halted = True
                if g is not HALT:
                    bad += 1
                break
            regs, pc = nxt
            if g is HALT or g != enc(regs, pc):
                bad += 1
                break
            n = g
            steps += 1
        if not halted or regs[0] != expect(regs0):
            wrong += 1
    return gam, bad, steps, wrong


# ---------------------------------------------------------------- PRIMEGAME
PRIMEGAME = [(17, 91), (78, 85), (19, 51), (23, 38), (29, 33), (77, 29),
             (95, 23), (77, 19), (1, 17), (11, 13), (13, 11), (15, 2),
             (1, 7), (55, 1)]


def primegame_powers(cap, want):
    """Exponents e such that 2^e occurs in the PRIMEGAME orbit from 2."""
    g = ResGAM(PRIMEGAME, "PRIMEGAME")
    x, out = 2, []
    for _ in range(cap):
        x = g.step(x)
        if x is HALT:
            break
        if x & (x - 1) == 0:                        # a pure power of 2
            out.append(x.bit_length() - 1)
            if len(out) >= want:
                break
    return out


def is_prime(n):
    if n < 2:
        return False
    d = 2
    while d * d <= n:
        if n % d == 0:
            return False
        d += 1
    return True


# --------------------------------------------------------------------- main
ADD = [("dec", 1, 1, 2),                                       # r0 += r1
       ("inc", 0, 0)]
MUL = [("dec", 1, 1, 6),                                       # r0 += r1*r2
       ("dec", 2, 2, 4), ("inc", 0, 3), ("inc", 3, 1),
       ("dec", 3, 5, 0), ("inc", 2, 4)]


def main():
    print("WS4.1  THE SIZE FRONTIER IN ONE SYNTAX\n")

    print("(1) register machine -> RES-GAM, step-exact")
    for label, prog, nregs, starts, expect in [
        ("ADD  r0 += r1", ADD, 4, [(a, b, 0, 0) for a in range(6) for b in range(6)],
         lambda s: s[0] + s[1]),
        ("MUL  r0 += r1*r2", MUL, 4,
         [(a, b, c, 0) for a in range(4) for b in range(4) for c in range(4)],
         lambda s: s[0] + s[1] * s[2]),
    ]:
        gam, bad, steps, wrong = check_step_exact(prog, nregs, starts, expect)
        print(f"  {label:18s} {len(prog)} instr -> {len(gam.fr):2d} rules "
              f"(<= 2I = {2 * len(prog)}), modulus {gam.modulus():,}")
        print(f"  {'':18s} lockstep mismatches over {steps:,} steps: {bad}; "
              f"starts computing the wrong answer: {wrong}/{len(starts)}")
    print("  => an I-instruction register machine compiles to <= 2I rules,")
    print("     step for step.  With Minsky's theorem, RES-GAMs are universal,")
    print("     and the smallest universal I gives an upper bound of 2I rules.\n")

    print("(2) PRIMEGAME -- a 14-rule RES-GAM, verified rather than cited")
    g = ResGAM(PRIMEGAME, "PRIMEGAME")
    got = primegame_powers(200_000, 15)
    print(f"  rules {len(g.fr)}, modulus {g.modulus():,}")
    print(f"  pure powers 2^e in the orbit from 2:  e = {got}")
    print(f"  all prime: {all(is_prime(e) for e in got)};  "
          f"consecutive primes from 2: {got == [p for p in range(2, 100) if is_prime(p)][:len(got)]}")
    print("  => unbounded nontrivial computation at 14 rules, one counter.\n")

    print("(3) where the cryptids sit -- and what that does NOT prove")
    print("  Needle    1 counter, VAL(2), ONE schema: F(x) = (2^(v+1)+3)k + (2^v+v)")
    print("  machine 3 1 counter, VAL(3), ONE schema: G(a) = (3^(j+1)+1)m + (r*3^j+j+c_r)")
    print("  Fenrir    1 counter, RES-style, 2 branches (a FRACTRAN cryptid)")
    print("  Written size is below PRIMEGAME's 14 rules.  But VAL(q) unfolds one")
    print("  schema into infinitely many affine pieces, so smaller ON THE PAGE is")
    print("  not smaller IN POWER.  No result here, and none we know of, lower-")
    print("  bounds the power of a 1-schema VAL machine.  The frontier is an")
    print("  UPPER bound on where universality starts, nothing more.")


if __name__ == "__main__":
    main()
