"""What VAL(2) cannot do, and the far more useful fact about what cannot prove it.

WS4 left one open question: is the one-schema VAL(2) class Turing-complete?
This file does not settle it.  It proves a barrier over an explicit slice of the
family, and -- more valuably -- it refutes the whole genre of argument the
program had planned to use, with a reason that applies to every member of that
genre.

NAMING.  T1-T11 are non-halting machines (census/); T12 is delta-saturation
(census/saturation.py).  R and T13 are here.

--------------------------------------------------------------------------
THEOREM R -- BRANCH RIGIDITY (proved).

  Branch v sends every non-halting input to the SAME valuation
      <=>  v_2(B_v) < v_2(A_v)      (with v_2(0) = infinity)
  and in that case v_2(F(x)) = v_2(B_v) for every x on the branch.

PROOF.  Write A_v = 2^a A', B_v = 2^b B' with A', B' odd.  If b < a then
F(x) = 2^b (2^(a-b) A' k + B') and the bracket is odd for every k, so v_2 = b
always.  If b >= a then F(x) = 2^a (A' k + 2^(b-a) B'), and A' is a unit mod any
power of two, so A'k + 2^(b-a)B' realises every residue as k varies; its
valuation is therefore unbounded, and in particular not constant.  QED

--------------------------------------------------------------------------
T13 -- THE BARRIER THEOREM (proved).

  If v_2(B_v) < v_2(A_v) for every v, then every orbit's branch sequence is a
  fixed sequence, independent of the state: v_(n+1) = v_2(B_{v_n}) is a function
  of v_n alone.  It is therefore eventually periodic, the orbit is a periodic
  composition of affine maps, and x_n has a closed form c*lambda^n + d.

  Such a machine performs NO state-dependent branching and cannot carry a
  computation.  Its halting question degenerates to an S-unit equation
  "c*lambda^n + d = 2^t", which is not the hard kind.

CLOSED FORM, and the correction that verification forced.  For beta EVEN and
NONZERO, with a = v_2(beta) >= 1: global rigidity holds iff the finitely many
branches v < a are rigid AND gcd(delta, 2^a) does not divide epsilon.  (For
v >= a we have v_2(A_v) = a and B_v = delta*v + epsilon mod 2^a, and delta*v
sweeps the subgroup generated by gcd(delta, 2^a).)  **This criterion silently
omits beta = 0**, which is a genuinely different case rather than a degenerate
one: A_v = alpha*2^(v+1) has v_2(A_v) = v+1 growing without bound, so rigidity
there is generic instead of exceptional.  In the box below, beta = 0 supplies
758 of the 2,351 rigid machines -- almost a third.  The criterion was stated
without it, and the omission survived the original author's own verification
because the check ranged over beta even and the failures were read as a bug.

--------------------------------------------------------------------------
THE REFUTATION, which is the point of the file.

The plan was to prove VAL(2) too poor to be universal by counting: (A_v, B_v)
mod M depends on v only through (2^v mod M, v mod M), so the branch table is
eventually periodic in v with period dividing lcm(ord_M(2), M) -- while a
Conway / Kurtz-Simon reduction with modulus M needs M independent affine pieces.
The periodicity is TRUE (and verified below).  The conclusion does not follow:
measured branch bandwidth -- the number of distinct (A_v, B_v) mod M actually
achieved -- is at least M for every modulus tested.  VAL(2) supplies at least as
many distinct branch behaviours as such a reduction consumes.

And the reason generalises past this one attempt:

  **Universality is a property of a single point, not of a family.**

A 5-parameter family of dimension 5 inside a 2V-dimensional space of branch
tables can still contain a universal machine, because a universal machine is a
0-parameter object.  Every argument of the form "too few degrees of freedom",
"rank at most 5", "density M^(5-2V)", "bandwidth too small" is therefore
answering a question nobody asked.  This retires the entire counting genre --
including the composite-step version, where the dimension bound survives at 5
for every step count and is equally useless.

What a real barrier needs is a property shared by EVERY point of the family.
Theorem R is one, but it holds only on the beta-even slice.  The other is the
slope spectrum s_v = alpha + beta*2^-(v+1), which converges geometrically for
every machine: at most floor(log2(|beta|/rho)) branches are pairwise rho-
separated in slope, so k separated branches cost |beta| >= rho*2^(k-1).  That is
an exponential compression bound, not an impossibility -- and stating it that
way is the honest end of this line of attack.
"""
import random
import sys
from math import gcd, log2

sys.path.insert(0, "/Users/tomzahavy/Documents/Claude/collatz/census")
from family import Machine

BOX = [(a, b, g, d, e)
       for a in range(0, 4) for b in range(-4, 9)
       for g in range(-3, 5) for d in range(-3, 5) for e in range(-3, 5)]
INF = 10 ** 9


def v2(n):
    if n == 0:
        return INF
    c = 0
    while n % 2 == 0:
        n //= 2
        c += 1
    return c


def wd():
    return [t for t in BOX if Machine(*t).well_defined(2000)]


def step1_recurrences():
    print("STEP 1 -- THE BRANCH TABLES OBEY TWO MACHINE-INDEPENDENT RECURRENCES")
    print("-" * 72)
    random.seed(11)
    bad = 0
    for _ in range(4000):
        m = Machine(*[random.randint(-40, 40) for _ in range(5)])
        for v in range(40):
            bad += m.A(v + 2) != 3 * m.A(v + 1) - 2 * m.A(v)
            bad += m.B(v + 3) != 4 * m.B(v + 2) - 5 * m.B(v + 1) + 2 * m.B(v)
    print("  A_(v+2) = 3A_(v+1) - 2A_v   and   B_(v+3) = 4B_(v+2) - 5B_(v+1) + 2B_v")
    print("  4000 random machines x 40 branches: %d violations" % bad)
    print("  (characteristic polynomials (X-2)(X-1) and (X-2)(X-1)^2 -- the whole")
    print("   family lies on one 5-dimensional solution space)")
    return bad == 0


def step2_rigidity():
    print("\nSTEP 2 -- THEOREM R: rigid <=> v_2(B_v) < v_2(A_v)")
    print("-" * 72)
    random.seed(5)
    mism = tested = 0
    for t in random.sample(BOX, 1500):
        m = Machine(*t)
        if not m.well_defined(2000):
            continue
        for v in range(6):
            vals = set()
            for k in range(1, 900):
                y = m.step((1 << (v + 1)) * k + (1 << v))
                if y != "HALT" and y >= 1:
                    vals.add(v2(y))
            if not vals:
                continue
            tested += 1
            pred = v2(m.B(v)) < v2(m.A(v))
            if pred != (len(vals) == 1):
                mism += 1
            elif pred and next(iter(vals)) != v2(m.B(v)):
                mism += 1
    print("  %d (machine, branch) pairs, k <= 899: %d disagreements"
          % (tested, mism))
    return mism == 0


def step3_barrier(machines):
    print("\nSTEP 3 -- T13: how much of the family is provably computation-free")
    print("-" * 72)

    def rigid(m, vmax=200):
        return all(v2(m.B(v)) < v2(m.A(v)) for v in range(vmax))

    def criterion(t):
        """The stated closed form -- beta even and NONZERO only."""
        a_, b, g, d, e = t
        if b == 0 or b % 2:
            return False
        a = v2(b)
        m = Machine(*t)
        if not all(v2(m.B(v)) < v2(m.A(v)) for v in range(a)):
            return False
        return e % (gcd(d, 1 << a) if d else (1 << a)) != 0

    R = {t for t in machines if rigid(Machine(*t))}
    nz = [t for t in machines if t[1] % 2 == 0 and t[1] != 0]
    z = [t for t in machines if t[1] == 0]
    C = {t for t in nz if criterion(t)}
    print("  well-defined machines in the box: %d" % len(machines))
    print("  globally rigid (direct check, v < 200): %d  (%.2f%%)"
          % (len(R), 100.0 * len(R) / len(machines)))
    print("  all of them have beta even: %s" % all(t[1] % 2 == 0 for t in R))
    print("  criterion exact on beta even and NONZERO (%d machines): %s (%d rigid)"
          % (len(nz), (R & set(nz)) == C, len(C)))
    print("  beta = 0 (%d machines): %d rigid -- the case the criterion omits"
          % (len(z), len(R & set(z))))
    m0 = Machine(1, 0, 1, 1, 0)
    print("    e.g. (1,0,1,1,0): v_2(A_v) for v = 0..5 is %s -> unbounded, so"
          % [v2(m0.A(v)) for v in range(6)])
    print("    rigidity is generic there, not exceptional")
    return (R & set(nz)) == C


def step4_counting_fails():
    print("\nSTEP 4 -- THE COUNTING BARRIER IS REFUTED: bandwidth is at least M")
    print("-" * 72)
    random.seed(7)
    ok = True
    for M in (23, 101, 257):
        best = 0
        for _ in range(400):
            m = Machine(*[random.randint(-60, 60) for _ in range(5)])
            best = max(best, len({(m.A(v) % M, m.B(v) % M)
                                  for v in range(4 * M + 8)}))
        print("  M = %-4d best bandwidth over 400 random machines: %-5d  "
              ">= M: %s" % (M, best, best >= M))
        ok &= best >= M
    print("  A Conway-style reduction mod M needs M independent branch pieces.")
    print("  VAL(2) supplies at least that many -- so periodicity, while true,")
    print("  yields a structure theorem and NOT an impossibility.")
    return ok


def step5_slope():
    print("\nSTEP 5 -- WHAT SURVIVES: the slope-resolution bound (every machine)")
    print("-" * 72)
    random.seed(13)
    bad = n = 0
    for _ in range(3000):
        b = random.choice([x for x in range(-60, 61) if x])
        m = Machine(random.randint(1, 5), b, 1, 0, 0)
        for rho in (0.5, 0.1, 0.01):
            n += 1
            cnt = sum(1 for v in range(200)
                      if abs(m.A(v) / 2.0 ** (v + 1) - m.a) >= rho)
            if cnt != max(0, int(log2(abs(b) / rho)) if abs(b) >= rho else 0):
                bad += 1
    print("  #{v : |s_v - alpha| >= rho} = floor(log2(|beta|/rho))")
    print("  %d (machine, rho) pairs: %d mismatches" % (n, bad))
    print("  => k branches pairwise rho-separated in slope cost |beta| >= "
          "rho*2^(k-1):")
    print("     an EXPONENTIAL compression bound, not an impossibility.")
    return bad == 0


def main():
    machines = wd()
    r = [step1_recurrences(), step2_rigidity(), step3_barrier(machines),
         step4_counting_fails(), step5_slope()]
    print("\n" + "=" * 72)
    if all(r):
        print("RESULT: R and T13 proved; the counting barrier is refuted, and the")
        print("reason retires the genre -- universality is a property of a single")
        print("point, not of a family. VAL(2) universality remains OPEN.")
    else:
        print("RESULT: FAILED -- do not update the reports")


if __name__ == "__main__":
    main()
