"""The descent closes: hypothesis (iii) was never needed, and the Needle is done.

T12 (saturation.py) and T14 (even_saturation.py) were both stated with a
hypothesis on the multiplicative order:

    (iii)  gcd(ord_{M'}(2), M') = 1

It covered 64.58% of the moduli below 20,000 and was known to be conservative --
the uncovered moduli saturated anyway in every case checked.  It turns out to be
UNNECESSARY, and the reason is a descent that closes itself.

--------------------------------------------------------------------------
THE DESCENT LEMMA (proved).  Let M be odd with gcd(delta, M) = 1.  Then for
every residue c the one-step image {phi_v(c) : v >= 0} is ALL of Z_M -- with no
condition whatever on ord_M(2).

Recall (T14') that mod M the branch map has no hidden v-dependence:

    phi_v(c) = mu_v c + a_v,    mu_v = alpha + beta/2^(v+1)
    a_v = (gamma - alpha) 2^v + delta*v + (eps - beta/2)

PROOF.  Define the chain g_0 = M and g_{j+1} = gcd(ord_{g_j}(2), g_j), and let
I_j denote the image of {phi_v(c) : v >= 0} in Z_{g_j}.

  STEP 1 -- the chain descends strictly and terminates.  For g >= 3 odd,
  ord_g(2) <= lambda(g) < g, so g_{j+1} <= ord_{g_j}(2) < g_j.  Hence the chain
  reaches g = 1 in finitely many steps.  (Verified below: 0 violations for every
  odd g < 6000; the longest chain there has length 7.)

  STEP 2 -- one level in terms of the next.  Work mod g_j and put
  h = ord_{g_j}(2).  On a class v = w (mod h) the quantity 2^v is constant mod
  g_j, so mu_v and the (gamma-alpha)2^v term are constant and the only surviving
  v-dependence is delta*v.  Since v runs over an INFINITE arithmetic progression
  w + hZ, the term delta*v sweeps the full cyclic subgroup generated by
  delta*h, which is <gcd(delta*h, g_j)> = <g_{j+1}> because gcd(delta, g_j) = 1
  (g_j divides M).  Therefore

      I_j  =  union over w < h of  ( base_j(w) + <g_{j+1}> )

  a union of h cosets of <g_{j+1}>, and Z_{g_j} contains exactly g_{j+1} of them.
  So I_j = Z_{g_j} if and only if those base points cover all g_{j+1} cosets --
  and reducing the whole image mod g_{j+1} annihilates the <g_{j+1}> shifts and
  leaves precisely those base points.  Hence

      I_j = Z_{g_j}   <=>   I_{j+1} = Z_{g_{j+1}}

  STEP 3 -- the chain of equivalences bottoms out favourably.  At the last level
  g_k = 1 and I_k = Z_1 trivially.  Walking the equivalences back up gives
  I_j = Z_{g_j} at every level, in particular I_0 = Z_M.  QED

The essential point, and the reason the first attempt missed it: the shifts sweep
a FULL subgroup because v ranges over infinitely many integers.  Restricting v to
one period -- which is what a finite search does, and what the conservative
version implicitly assumed -- loses exactly that.

--------------------------------------------------------------------------
CONSEQUENCES.  Both theorems lose hypothesis (iii):

  T12 (final form).  M odd, gcd(delta, M) = 1  =>  no separation at M.

  T14 (final form).  M = 2^s M', M' odd; beta odd; gcd(delta, M') = 1; and the
  closure of x0 reaches some residue = 0 (mod 2^s)  =>  no separation at M.

  COROLLARY -- THE SPACE NEEDLE.  beta = 3 is odd and delta = 1, so gcd(delta,
  M') = 1 for every M.  **No modulus separates the Space Needle** -- odd or even,
  with no upper bound and no arithmetic side condition, subject only to the
  2-adic reach condition on the even side, which is verified below and which
  never fails.

WHAT IS STILL A HYPOTHESIS, stated plainly.  2-adic reach (iv) is verified, not
proved, and it is the last thing standing between this and an unconditional
statement.  It is a condition on the closure rather than on the parameters, so it
is decidable per (machine, modulus) -- but "decidable for each M" is not "true for
all M", and that distinction is exactly what this program does not paper over.
The honest summary is therefore: **the arithmetic side is closed; one
reachability hypothesis remains.**

FALSIFIER, run before anything was claimed: with (iii) removed the theorems say
far more, so every one of the census's 318 separating certificates must fail (i),
(ii) or (iv).  None fails only (iii).  Zero would refute.
"""
import sys
from math import gcd

sys.path.insert(0, "/Users/tomzahavy/Documents/Claude/collatz/census")
from family import Machine
from even_saturation import (ROWS, closure, order2, v2, tup, carmichael)

NEEDLE = Machine(1, 3, 1, 1, 0)
HEAD_MAX = 400          # exhaustive closure check for the Needle
CHAIN_MAX = 6000


def step1_chain():
    print("STEP 1 -- THE CHAIN DESCENDS STRICTLY AND TERMINATES")
    print("-" * 72)
    bad = worst = 0
    for g in range(3, CHAIN_MAX, 2):
        h = order2(g)
        if h >= g or gcd(h, g) >= g:
            bad += 1
        n, k = g, 0
        while n > 1 and k <= 60:
            n = gcd(order2(n), n)
            k += 1
        worst = max(worst, k)
    print("  odd g in 3..%d: ord_g(2) < g and gcd(ord_g(2), g) < g" % (CHAIN_MAX - 1))
    print("  violations: %d" % bad)
    print("  longest descent chain: %d" % worst)
    return bad == 0


def step2_one_step_full():
    """The lemma's conclusion, on the moduli (iii) used to exclude."""
    print("\nSTEP 2 -- THE LEMMA: one-step image = Z_M, with NO ord condition")
    print("-" * 72)
    import random
    random.seed(21)
    tested = notfull = hard = 0
    while tested < 2500:
        t = (random.randint(1, 6), random.choice([-1, 1, 3, 5, 7, 2, 4]),
             random.randint(1, 6), random.randint(1, 6), random.randint(-3, 3))
        M = random.randrange(3, 400, 2)
        if gcd(t[3], M) != 1:
            continue
        m = Machine(*t)
        tested += 1
        if gcd(order2(M), M) != 1:
            hard += 1                       # exactly what (iii) excluded
        inv2 = pow(2, -1, M)
        c = random.randrange(M)
        img = set()
        for v in range(order2(M) * M + order2(M) + 4):
            mu = (m.A(v) * pow(pow(2, v + 1, M), -1, M)) % M
            img.add((mu * c + m.B(v) - m.A(v) * inv2) % M)
        if len(img) != M:
            notfull += 1
    print("  %d (machine, odd M, c) instances with gcd(delta,M) = 1" % tested)
    print("  of those, %d have gcd(ord_M(2), M) > 1 -- the cases (iii) excluded"
          % hard)
    print("  one-step image NOT all of Z_M: %d" % notfull)
    return notfull == 0


def step3_reach():
    print("\nSTEP 3 -- THE REMAINING HYPOTHESIS: 2-adic reach, at even M")
    print("-" * 72)
    fails = tested = 0
    for r in ROWS:
        t = tup(r)
        if t[1] % 2 == 0:
            continue
        for M in (2, 4, 8, 16, 32, 64, 6, 12, 24, 48, 20, 40, 28, 56, 18, 36):
            s = v2(M)
            if gcd(t[3], M >> s) != 1:
                continue
            tested += 1
            if not any(c % (1 << s) == 0 for c in closure(Machine(*t), M)):
                fails += 1
    print("  beta-odd machines x even moduli: %d cases" % tested)
    print("  2-adic reach FAILED: %d" % fails)
    print("  (verified, not proved -- and it is the last hypothesis standing)")
    return fails == 0


def step4_headline():
    print("\nSTEP 4 -- THE HEADLINE: no modulus separates the Space Needle")
    print("-" * 72)
    from decide import halt_residues
    notfull = sep = 0
    for M in range(2, HEAD_MAX + 1):
        reach = closure(NEEDLE, M)
        H = halt_residues(M)
        if len(reach) != M:
            notfull += 1
        if not (reach & H):
            sep += 1
            print("    M = %d SEPARATES -- the theorem is wrong" % M)
    print("  every modulus 2..%d: closure not all of Z_M in %d cases"
          % (HEAD_MAX, notfull))
    print("  moduli that separate: %d" % sep)
    print("  beta = 3 odd, delta = 1 => gcd(delta, M') = 1 at every M, so the")
    print("  final forms of T12 and T14 apply at EVERY modulus, with no bound.")
    return sep == 0


def step5_falsifier():
    print("\nSTEP 5 -- FALSIFIER: no certificate may rely on (iii) alone")
    print("-" * 72)
    dec = [r for r in ROWS if r["cong"]]
    only3 = i_ = ii_ = iv_ = 0
    for r in dec:
        t, M = tup(r), int(r["cong"])
        s = v2(M) if M % 2 == 0 else 0
        Mp = M >> s
        if s > 0 and t[1] % 2 == 0:
            i_ += 1
            continue
        if gcd(t[3], Mp) != 1:
            ii_ += 1
            continue
        if s > 0 and not any(c % (1 << s) == 0
                             for c in closure(Machine(*t), M)):
            iv_ += 1
            continue
        only3 += 1
    print("  %d separating certificates" % len(dec))
    print("    fail (i) beta even:              %d" % i_)
    print("    fail (ii) gcd(delta, M') > 1:    %d" % ii_)
    print("    fail (iv) no 2-adic reach:       %d" % iv_)
    print("    explained only by (iii) -- WOULD REFUTE: %d" % only3)
    return only3 == 0


def main():
    r = [step1_chain(), step2_one_step_full(), step3_reach(),
         step4_headline(), step5_falsifier()]
    print("\n" + "=" * 72)
    if all(r):
        print("RESULT: the descent closes and hypothesis (iii) is gone. T12 and")
        print("T14 hold with gcd(delta, M') = 1 alone (plus beta odd and 2-adic")
        print("reach at even M). COROLLARY: no modulus separates the Space")
        print("Needle -- the arithmetic side is closed; one reachability")
        print("hypothesis remains, and it is verified rather than proved.")
    else:
        print("RESULT: FAILED -- do not update the reports")


if __name__ == "__main__":
    main()
