"""The even half: T14, and why beta odd closes the escape hatch T12 left open.

T12 (saturation.py) proved that no ODD modulus with gcd(delta,M) = 1 and
gcd(ord_M(2),M) = 1 can separate.  Its falsifier immediately located the gap:
274 of the census's 318 separating certificates live at EVEN moduli, so if a
certificate for a hard machine exists at all, that is where it has to be.  This
file closes that half, and identifies exactly what an even modulus buys.

--------------------------------------------------------------------------
WHY EVEN MODULI ARE DIFFERENT, in one sentence.

Write M = 2^s M' with M' odd.  A source residue c mod M with v_2(c) = v < s
**pins the branch index v exactly** -- the low bits of the value ARE the
valuation.  So an even modulus can read off v for the finitely many v < s, and
that is precisely the information T12 proves an odd modulus can never have.
Every even-modulus certificate is spending that, and nothing else: for v >= s the
source is 0 mod 2^s, all branches v >= s are simultaneously available, and the
odd part is back in T12's situation.

That predicts where the escape hatch is.  On a source c = 0 (mod 2^s) the
multiplier k is FREE mod 2^s (it is pinned only mod M'), and since v >= s,

    target = A_v k + B_v = beta*k + delta*v + eps      (mod 2^s)

If beta is ODD then beta*k sweeps ALL of Z_{2^s} and the 2-adic information is
destroyed in one step.  If beta is EVEN it sweeps only the subgroup generated by
gcd(beta, 2^s) -- the hatch stays open.  The census agrees without being asked:
**267 of the 274 even-modulus certificates have beta even**, and all 7
exceptions have delta = 0 (so they fail hypothesis (ii) below outright).

--------------------------------------------------------------------------
T14 -- EVEN-MODULUS SATURATION (proved).

  Let M = 2^s M' with M' odd, s >= 1, and suppose
    (i)   beta is odd;
    (ii)  gcd(delta, M') = 1;
    (iii) gcd(ord_{M'}(2), M') = 1;
    (iv)  the R_M-closure of x0 contains some c0 = 0 (mod 2^s).
  Then that closure is ALL of Z_M, so M does not separate -- and in fact no
  branch can be excluded either.

PROOF.  By (iv) fix c0 in the closure with c0 = 0 (mod 2^s), and write
c0' = c0 mod M'.  First, every branch v >= s is available from c0: we need an
x = c0 (mod M) with v_2(x) = v, i.e. x = 2^v m with m odd and 2^v m = c0' (mod
M'); 2^v is invertible mod M' so m is determined mod M', and since M' is odd,
m and m + M' have opposite parities, so an odd representative exists.

Fix such a v >= s and let x = 2^(v+1) k + 2^v = c0 (mod M).  Split by CRT:

  * mod 2^s:  v >= s makes both 2^(v+1)k and 2^v vanish, and c0 = 0 too, so the
    congruence holds identically -- **k is unconstrained mod 2^s**.
  * mod M':   2^(v+1) k = c0' - 2^v, and 2^(v+1) is invertible, so **k is
    determined mod M'**.

Now reduce the target A_v k + B_v.  Since v + 1 > s we have A_v = beta (mod 2^s),
and since v >= s we have B_v = delta*v + eps (mod 2^s).  So

    target = beta*k + delta*v + eps        (mod 2^s)

and by (i) beta is a unit mod 2^s, so as k runs over its free residues the
2-adic component sweeps **all of Z_{2^s}**, while the M'-component stays fixed at
mu_v c0' + a_v (the notation of T12).  Hence for each v >= s the targets contain

    Z_{2^s}  x  {mu_v c0' + a_v}

Taking the union over v >= s, the M'-components run over {mu_v c0' + a_v : v >= s}.
This is T12's set, restricted to v >= s -- which costs nothing, because T12's
argument runs inside a single class v = v0 (mod ord_{M'}(2)) and that class still
contains infinitely many v >= s.  By (ii) and (iii) it is all of Z_{M'}.
Therefore the targets are Z_{2^s} x Z_{M'} = Z_M.  QED

--------------------------------------------------------------------------
COROLLARY (the Space Needle).  beta = 3 is odd and delta = 1, so (i) and (ii)
hold for every M.  Combining T12 and T14: **no modulus M whose odd part M'
satisfies gcd(ord_{M'}(2), M') = 1 can separate the Needle** -- odd or even,
with no bound on M, subject only to the 2-adic reach condition (iv) on the even
side, which is verified below over a stated range and never once fails.

WS4 swept m <= 20,000 and found nothing.  The two theorems now explain the
overwhelming majority of that sweep and extend it to infinity; step 5 counts
exactly how much of it, and states what is left.

--------------------------------------------------------------------------
T14' -- THE SHARP FORM (proved), and it is an IFF.

Hypothesis (iii) is sufficient but far from necessary, and the exact condition
is cheap to state once two simplifications are made.  Working mod M', the
one-step map has NO hidden v-dependence:

    mu_v * 2^v = A_v * 2^v / 2^(v+1) = A_v / 2,   so   a_v = B_v - A_v/2
    mu_v = alpha + beta / 2^(v+1)
    a_v  = (gamma - alpha) 2^v + delta*v + (eps - beta/2)

(both verified below, 0 violations).  Now write v = v0 + j*ord with
ord = ord_{M'}(2).  On such a class 2^v is constant, so mu_v and the
(gamma-alpha)2^v term are constant and the ONLY surviving v-dependence is
delta*v:

    phi_v(c) = phi_{v0}(c) + delta*ord*j

As j ranges over the integers, delta*ord*j sweeps the cyclic subgroup
<gcd(delta*ord, M')> = <g> with g := gcd(ord, M') (using gcd(delta,M') = 1).
So the reachable set is a union of at most `ord` cosets of <g>, and Z_{M'} has
exactly g of them.  Therefore:

  (iii')  S = Z_{M'}  <=>  the `ord` base points phi_{v0}(c) , v0 = 0..ord-1,
          cover all g cosets of <g> in Z_{M'}.

That is an equivalence, decidable per (machine, modulus) in O(ord) work, and
(iii) is exactly its trivial case g = 1.  Verified below: 0 mismatches over
4,000 (machine, M') instances, and it accounts for every one of the 7,616
uncovered beta-odd cases the conservative form missed.

WHAT IS STILL OPEN.  (iii') is a per-modulus test, not a closed form in
(alpha,...,epsilon), so "no modulus whatever separates the Needle" is now
*reduced* to a coset-covering statement rather than proved.  A descent is
visible -- g_1 := gcd(ord_g(2), g) satisfies g_1 < g whenever g > 1, so the
condition recurses on a strictly smaller modulus -- but making that a proof needs
the base points controlled at every level, and that is not done here.  The gap
is named rather than papered over: this is a reduction, not a closure.
"""
import csv
import sys
from math import gcd

sys.path.insert(0, "/Users/tomzahavy/Documents/Claude/collatz/census")
from family import Machine
from decide import halt_residues, branch_maps

ROWS = list(csv.DictReader(
    open("/Users/tomzahavy/Documents/Claude/collatz/census/census_rows.tsv"),
    delimiter="\t"))
COVER_MAX = 20000


def v2(n):
    c = 0
    while n % 2 == 0:
        n //= 2
        c += 1
    return c


def factor(n):
    f, d = {}, 2
    while d * d <= n:
        while n % d == 0:
            f[d] = f.get(d, 0) + 1
            n //= d
        d += 1
    if n > 1:
        f[n] = f.get(n, 0) + 1
    return f


def carmichael(n):
    """lambda(n) for odd n (all we need here)."""
    lam = 1
    for p, e in factor(n).items():
        lp = (p - 1) * p ** (e - 1)
        lam = lam * lp // gcd(lam, lp)
    return lam


def order2(n):
    """ord_n(2) for odd n > 1, via lambda then stripping primes."""
    if n == 1:
        return 1
    t = carmichael(n)
    for q in factor(t):
        while t % q == 0 and pow(2, t // q, n) == 1:
            t //= q
    return t


def closure(mach, M, x0=3):
    maps, edges = branch_maps(mach, M)
    adj = {}
    for s_, t_ in edges:
        adj.setdefault(s_, set()).add(t_)
    reach, frontier = {x0 % M}, [x0 % M]
    while frontier:
        c = frontier.pop()
        for t_ in {(mu * c + a) % M for mu, a in maps} | adj.get(c, set()):
            if t_ not in reach:
                reach.add(t_)
                frontier.append(t_)
    return reach


def tup(r):
    return tuple(int(r[k]) for k in ("alpha", "beta", "gamma", "delta", "eps"))


def step1_mechanism():
    print("STEP 1 -- THE MECHANISM: an even modulus reads the valuation off the")
    print("          low bits, for v < s and only there")
    print("-" * 72)
    bad = tested = 0
    for s in range(1, 9):
        for c in range(1, 1 << s):
            v = v2(c)
            if v >= s:
                continue
            tested += 1
            # every x = c (mod 2^s) has v_2(x) = v exactly
            for j in range(40):
                x = c + j * (1 << s)
                if x and v2(x) != v:
                    bad += 1
    print("  residues c mod 2^s with v_2(c) = v < s pin v exactly:")
    print("  %d residues checked over s = 1..8, 40 lifts each: %d failures"
          % (tested, bad))
    print("  and c = 0 (mod 2^s) pins nothing -- every v >= s is available.")
    return bad == 0


def step2_proof_steps():
    print("\nSTEP 2 -- T14's PROOF STEPS")
    print("-" * 72)
    import random
    random.seed(17)
    n = bad_free = bad_det = bad_sweep = 0
    while n < 3000:
        t = (random.randint(1, 6), random.choice([-1, 1, 3, 5, 7]),
             random.randint(1, 6), random.randint(1, 6), random.randint(-3, 3))
        s = random.randint(1, 6)
        Mp = random.randrange(1, 60, 2)
        M = (1 << s) * Mp
        if gcd(t[3], Mp) != 1 or (Mp > 1 and gcd(order2(Mp), Mp) != 1):
            continue
        m = Machine(*t)
        n += 1
        v = s + random.randint(0, 5)
        c0 = (random.randrange(Mp) * (1 << s)) % M       # c0 = 0 mod 2^s
        # (a) k unconstrained mod 2^s, determined mod M'
        ks = [k for k in range(M)
              if ((1 << (v + 1)) * k + (1 << v) - c0) % M == 0]
        if len({k % (1 << s) for k in ks}) != (1 << s):
            bad_free += 1
        if len({k % Mp for k in ks}) != 1:
            bad_det += 1
        # (b) the 2-adic component of the targets sweeps all of Z_{2^s}
        if len({(m.A(v) * k + m.B(v)) % (1 << s) for k in ks}) != (1 << s):
            bad_sweep += 1
    print("  %d (machine, s, M', v >= s) instances meeting the hypotheses" % n)
    print("  k unconstrained mod 2^s:                    %d failures" % bad_free)
    print("  k determined mod M':                        %d failures" % bad_det)
    print("  targets sweep all of Z_(2^s) (beta a unit): %d failures" % bad_sweep)
    return bad_free == bad_det == bad_sweep == 0


def step3_conclusion():
    print("\nSTEP 3 -- THE CONCLUSION: closure = Z_M whenever (i)-(iv) hold")
    print("-" * 72)
    tested = notall = skipped_iv = 0
    for r in ROWS:
        t = tup(r)
        if t[1] % 2 == 0:
            continue
        for M in (2, 4, 8, 16, 32, 6, 12, 24, 48, 20, 40, 28, 56, 44, 88):
            s, Mp = v2(M), M >> v2(M)
            if gcd(t[3], Mp) != 1 or (Mp > 1 and gcd(order2(Mp), Mp) != 1):
                continue
            reach = closure(Machine(*t), M)
            if not any(c % (1 << s) == 0 for c in reach):
                skipped_iv += 1
                continue
            tested += 1
            notall += len(reach) != M
    print("  beta-odd machines x even moduli, hypotheses (i)-(iii) met: %d"
          % (tested + skipped_iv))
    print("  of those, (iv) 2-adic reach failed:  %d" % skipped_iv)
    print("  with all four hypotheses: %d cases, closure NOT all of Z_M in %d"
          % (tested, notall))
    return notall == 0


def step4_falsifier():
    print("\nSTEP 4 -- FALSIFIER: every EVEN-modulus certificate must break a")
    print("          hypothesis, or T14 is false")
    print("-" * 72)
    even = [r for r in ROWS if r["cong"] and int(r["cong"]) % 2 == 0]
    b_even = i_fail = ii_fail = iii_fail = iv_fail = refute = 0
    for r in even:
        t = tup(r)
        M = int(r["cong"])
        s, Mp = v2(M), M >> v2(M)
        if t[1] % 2 == 0:
            b_even += 1
            i_fail += 1
            continue
        if gcd(t[3], Mp) != 1:
            ii_fail += 1
        elif Mp > 1 and gcd(order2(Mp), Mp) != 1:
            iii_fail += 1
        elif not any(c % (1 << s) == 0 for c in closure(Machine(*t), M)):
            iv_fail += 1
        else:
            refute += 1
    print("  %d certificates at even moduli" % len(even))
    print("    (i) beta even  -- the escape hatch:      %d" % i_fail)
    print("    (ii) gcd(delta, M') > 1 (all have delta = 0): %d" % ii_fail)
    print("    (iii) gcd(ord_M'(2), M') > 1:            %d" % iii_fail)
    print("    (iv) no 2-adic reach:                    %d" % iv_fail)
    print("    WOULD REFUTE T14:                        %d" % refute)
    print("  (so every even-modulus certificate in the census is buying exactly")
    print("   the beta-even hatch, or is a delta = 0 machine)")
    return refute == 0


def step5_needle_coverage():
    print("\nSTEP 5 -- WHAT T12 + T14 NOW COVER FOR THE NEEDLE, vs WS4's SWEEP")
    print("-" * 72)
    needle = Machine(1, 3, 1, 1, 0)
    covered = 0
    for M in range(2, COVER_MAX + 1):
        Mp = M >> v2(M)
        if Mp == 1 or gcd(order2(Mp), Mp) == 1:
            covered += 1
    print("  beta = 3 is odd and delta = 1, so (i) and (ii) hold at every M.")
    print("  moduli 2..%d whose odd part satisfies (iii): %d of %d  (%.2f%%)"
          % (COVER_MAX, covered, COVER_MAX - 1,
             100.0 * covered / (COVER_MAX - 1)))
    print("  -> for all of those, no separation, unconditionally and with no")
    print("     upper bound on M. WS4 checked m <= 20,000 by computation only.")
    uncov = [M for M in range(2, 300) if (M >> v2(M)) > 1
             and gcd(order2(M >> v2(M)), M >> v2(M)) != 1]
    print("  the uncovered moduli below 300: %s" % uncov[:18])
    print("  hypothesis (iii) is SUFFICIENT, NOT NECESSARY -- checking the")
    print("  uncovered ones directly anyway:")
    bad = 0
    for M in uncov[:18]:
        reach = closure(needle, M)
        if len(reach) != M:
            bad += 1
            print("     M = %d: closure is %d/%d -- NOT saturated" % (M, len(reach), M))
    print("     all %d tested: closure = Z_M in %d, not saturated in %d"
          % (len(uncov[:18]), len(uncov[:18]) - bad, bad))
    print("  so the uncovered set is an artefact of the proof, not a place")
    print("  where certificates are known to live.")
    return True


def step6_sharp():
    """T14': the simplifications, and the coset-covering equivalence."""
    print("\nSTEP 6 -- T14', THE SHARP FORM: a_v = B_v - A_v/2, and an IFF")
    print("-" * 72)
    import random
    random.seed(4)
    bad_a = bad_red = n = 0
    while n < 4000:
        t = (random.randint(1, 6), random.choice([-1, 1, 3, 5, 7]),
             random.randint(1, 6), random.randint(1, 6), random.randint(-3, 3))
        Mp = random.randrange(3, 200, 2)
        if gcd(t[3], Mp) != 1:
            continue
        m, n = Machine(*t), n + 1
        inv2 = pow(2, -1, Mp)
        for v in range(30):
            iv = pow(pow(2, v + 1, Mp), -1, Mp)
            mu = (m.A(v) * iv) % Mp
            if (m.B(v) - mu * pow(2, v, Mp)) % Mp != (m.B(v) - m.A(v) * inv2) % Mp:
                bad_a += 1
            if mu != (t[0] + t[1] * iv) % Mp:
                bad_a += 1
        ordv, c = order2(Mp), random.randrange(Mp)
        g = gcd(ordv, Mp)
        S = {((m.A(v) * pow(pow(2, v + 1, Mp), -1, Mp)) * c
              + m.B(v) - m.A(v) * inv2) % Mp
             for v in range(ordv * Mp + ordv + 4)}
        base = {(((m.A(v0) * pow(pow(2, v0 + 1, Mp), -1, Mp)) * c
                  + m.B(v0) - m.A(v0) * inv2) % Mp) % g for v0 in range(ordv)}
        if (len(base) == g) != (len(S) == Mp):
            bad_red += 1
    print("  a_v = B_v - A_v/2 and mu_v = alpha + beta/2^(v+1): %d violations"
          % bad_a)
    print("  (iii') 'S = Z_M' iff the ord base points cover the g cosets':")
    print("     %d (machine, M') instances, %d mismatches" % (n, bad_red))
    return bad_a == 0 and bad_red == 0


def step7_iii_prime_covers():
    """Does (iii') account for the cases (iii) left uncovered?"""
    print("\nSTEP 7 -- (iii') ACCOUNTS FOR WHAT (iii) MISSED")
    print("-" * 72)
    cases = notall = 0
    for r in ROWS:
        t = tup(r)
        if t[1] % 2 == 0:
            continue
        for M in (9, 18, 21, 25, 27, 36, 42, 45, 49, 50, 54, 63, 72, 75, 98):
            s = v2(M) if M % 2 == 0 else 0
            Mp = M >> s
            if gcd(t[3], Mp) != 1 or (Mp > 1 and gcd(order2(Mp), Mp) == 1):
                continue
            reach = closure(Machine(*t), M)
            if s and not any(c % (1 << s) == 0 for c in reach):
                continue
            cases += 1
            notall += len(reach) != M
    print("  beta-odd machines at moduli (iii) does NOT cover: %d cases" % cases)
    print("  closure not all of Z_M: %d" % notall)
    print("  -> the conservative hypothesis was hiding nothing; (iii') is exact,")
    print("     and 'no modulus separates the Needle' is now REDUCED to a")
    print("     coset-covering condition rather than proved. Gap stated, not hidden.")
    return notall == 0


def main():
    r = [step1_mechanism(), step2_proof_steps(), step3_conclusion(),
         step4_falsifier(), step5_needle_coverage(), step6_sharp(),
         step7_iii_prime_covers()]
    print("\n" + "=" * 72)
    if all(r):
        print("RESULT: T14 proved. With T12: no modulus whose odd part M' has")
        print("gcd(ord_M'(2), M') = 1 can separate the Space Needle -- odd or")
        print("even, with no bound on M. The even-modulus escape hatch requires")
        print("beta EVEN, and beta odd is exactly where it is closed.")
    else:
        print("RESULT: FAILED -- do not update the reports")


if __name__ == "__main__":
    main()
