"""Why no congruence decides the Needle: a theorem, not a search bound.

WS4 swept every modulus m <= 20,000 and found no separating congruence for the
Space Needle.  That is a bounded resource -- exactly the kind of result P9 warns
is silent past its budget.  This file replaces an infinite slice of that sweep
with a proof, and adds the congruence-criterion theorems at m = 4, 6, 8 that the
census left on the table after T3 did m = 3.

NAMING.  T1, T2, T4-T11 are machines that never halt (theorems.py, leads.py,
universal.py).  T3 is the m = 3 separation criterion; C4, C6, C8 below are its
companions at 4, 6, 8.  T12 is the saturation theorem.

--------------------------------------------------------------------------
T12 -- THE DELTA-SATURATION THEOREM (proved).

  Let a machine have parameters (alpha, beta, gamma, delta, epsilon) and let M
  be ODD with gcd(delta, M) = 1 and gcd(ord_M(2), M) = 1.  Then for EVERY
  residue c, the one-step image {phi_v(c) : v >= 0} is ALL of Z_M.

PROOF.  M odd makes 2^(v+1) invertible, so branch v is the single affine map

    phi_v(c) = mu_v c + a_v,   mu_v = A_v (2^(v+1))^{-1},  a_v = B_v - mu_v 2^v

(the source is x = 2^(v+1) k + 2^v = c, so k = (c - 2^v)/2^(v+1), and the target
is A_v k + B_v).  Fix v0 and restrict to v = v0 (mod ord_M(2)).  On that class
2^v mod M is constant, hence A_v mod M is constant, hence mu_v is constant; and
gamma*2^v is constant too.  So the ONLY surviving v-dependence in a_v is the
term delta*v:

    a_v - a_{v0} = delta*(v - v0)        (mod M)

As v runs over v0 + ord_M(2)*Z, the difference v - v0 runs over ord_M(2)*Z,
whose image in Z_M is the subgroup generated by gcd(ord_M(2), M) = 1 -- that is,
all of Z_M.  And gcd(delta, M) = 1 makes delta*(v - v0) run over all of Z_M as
well.  Hence {phi_v(c)} contains mu_{v0} c + a_{v0} + Z_M = Z_M.  QED

COROLLARY (the Space Needle).  delta = 1, so gcd(delta, p) = 1 for every odd
prime p; and ord_p(2) divides p - 1, so gcd(ord_p(2), p) = 1 automatically.
**No odd prime modulus can ever separate the Needle** -- not "none below the
search bound": none, unconditionally.  In fact no branch can even be excluded,
since already the one-step image from any residue is everything.

This sharpens T3's corollary.  T3 said the v-linear term blocks the cheapest
certificate (m = 3).  T12 says it blocks EVERY prime certificate TOTALLY, in a
single step, for reasons that have nothing to do with how large the prime is.

WHAT IT DOES NOT COVER.  Even M.  That is not a gap in the write-up but the
honest boundary of the argument: 2 is not invertible mod an even M, so a branch
is no longer a single affine map.  It matters, because 274 of the census's 318
separating certificates live at even moduli -- if a certificate for a hard
machine exists at all, that is where it must be.

--------------------------------------------------------------------------
THE CONGRUENCE CRITERIA.  Separation at m depends on (alpha,...,epsilon) only
through their residues mod m, so each criterion is a finite object on (Z_m)^5
and is checked COMPLETELY below, not sampled.  Write

    A0 = 2a+b,  B0 = g+e,  A1 = 4a+b,  B1 = 2g+d+e,  T = A0+B0,  U = A1+B1.

 T3 (already proved).  Separates at 3  <=>  d = 0, g = a, b + e = 0  (mod 3).

 C4 (proved).  Separates at 4  <=>  b even and 2a+b+g+e = 3 (mod 4).
    Mod 4 the powers of two are {1,2,0}, so H = {0,1,2} and the only allowed
    class is {3}, which holds x0 = 3; the closure must therefore be exactly {3}.
    Only v = 0 has odd sources, and x = 2k+1 = 3 (mod 4) iff k is odd, giving
    the two targets A0+B0 and 3A0+B0.  Both equal 3 iff 2A0 = 0 (mod 4) -- i.e.
    A0 even, i.e. b even -- and A0+B0 = 3 (mod 4).

 C6 (proved).  H = {1,2,4}, allowed {0,3,5}.  Separates at 6 iff one of
    (a) A0 even and T = 3 (mod 6)                               [closure {3}]
    (b) A0 = 0 or 4 (mod 6) and T = 5 (mod 6)                   [closure {3,5}]
    (c) T3 holds                                                [closure in {0,3}]
    (d) A0 = 0, B0 = 0 (mod 6), d = 0 (mod 3), g+d = b+5 (mod 6) [{0,3,5}]
    From 3 the targets are {T, T+3A0} and 3A0 is 0 or 3, so a subset of {0,3,5}
    forces {0,3}; that is (a).  From 5 they are {T+A0, T+4A0}; that is (b).  If
    0 is reached but 5 is not, all twelve targets out of 0 must lie in {0,3},
    i.e. A_v + B_v = 0 (mod 3) for all six v-classes, which forces d = 0, then
    g = a, then b + e = 0 (mod 3) -- exactly T3.  (d) is the residue.

 C8 (proved).  H = {0,1,2,4}, allowed {3,5,6,7}.  Only v = 0 and v = 1 can
    occur (v = 2 gives source 4, v >= 3 gives source 0, both halting).  A0 must
    be even: if A0 is odd, from 3 the targets are {T, T+4}, admissible only as
    {3,7}, and then from 7 the targets {T+2, T+6} always contain 1.  With A0
    even, 4A0 = 0 (mod 8) and the question is the forward orbit of 3 under the
    explicit four-node map 3 -> T, 5 -> T+A0, 7 -> T+2A0,
    6 -> {U + 2jA1 : j = 0..3}.

--------------------------------------------------------------------------
PROVENANCE.  T12 came out of asking why Bertok-Hajdu's Skolem-witness machinery
finds nothing here.  It does not apply -- their equations admit only exponents
as unknowns, and ours carry k and delta*v linearly -- but the question "why does
no witness modulus exist?" is better than "which witness works?", and this is
its answer.  The Skolem framing is a good orienting remark and not a tool; see
the meta report.
"""
import csv
import sys
from math import gcd
from itertools import product

sys.path.insert(0, "/Users/tomzahavy/Documents/Claude/collatz/census")
from family import Machine
from decide import halt_residues, branch_maps

ROWS = list(csv.DictReader(
    open("/Users/tomzahavy/Documents/Claude/collatz/census/census_rows.tsv"),
    delimiter="\t"))


def order(b, M):
    o, p = 1, b % M
    while p != 1:
        p, o = (p * b) % M, o + 1
    return o


def mu_a(m, v, M):
    tw = pow(2, v + 1, M)
    mu = (m.A(v) * pow(tw, -1, M)) % M
    return mu, (m.B(v) - mu * pow(2, v, M)) % M


def full_image(m, c, M, vmax):
    out = set()
    for v in range(vmax):
        k = ((c - pow(2, v, M)) * pow(pow(2, v + 1, M), -1, M)) % M
        out.add((m.A(v) * k + m.B(v)) % M)
    return out


def separates(mach, M, x0=3):
    """Exactly decide.congruence_proof's test, for one modulus."""
    H = halt_residues(M)
    c0 = x0 % M
    if c0 in H:
        return False
    maps, edges = branch_maps(mach, M)
    adj = {}
    for s, t in edges:
        adj.setdefault(s, set()).add(t)
    reach, frontier = {c0}, [c0]
    while frontier:
        c = frontier.pop()
        for t in {(mu * c + a) % M for mu, a in maps} | adj.get(c, set()):
            if t in H:
                return False
            if t not in reach:
                reach.add(t)
                frontier.append(t)
    return True


def T3(a, b, g, d, e):
    return d % 3 == 0 and (g - a) % 3 == 0 and (b + e) % 3 == 0


def C4(a, b, g, d, e):
    return b % 2 == 0 and (2 * a + b + g + e) % 4 == 3


def C6(a, b, g, d, e):
    A0, B0 = 2 * a + b, g + e
    T = (A0 + B0) % 6
    return ((A0 % 2 == 0 and T == 3)
            or (A0 % 6 in (0, 4) and T == 5)
            or T3(a, b, g, d, e)
            or (A0 % 6 == 0 and B0 % 6 == 0 and d % 3 == 0
                and (g + d - b - 5) % 6 == 0))


def step1_saturation():
    print("STEP 1 -- T12, THE DELTA-SATURATION THEOREM: its proof steps")
    print("-" * 72)
    import random
    random.seed(3)
    tested = bad_ab = bad_c = 0
    while tested < 4000:
        t = (random.randint(1, 6), random.choice([-1, 1, 3, 5, 7, 2, 4]),
             random.randint(1, 6), random.randint(1, 6), random.randint(-3, 3))
        M = random.randrange(3, 400, 2)
        if gcd(t[3], M) != 1:
            continue
        o = order(2, M)
        if gcd(o, M) != 1:
            continue
        m, d = Machine(*t), t[3]
        tested += 1
        for v0 in range(min(o, 6)):
            mu0, a0 = mu_a(m, v0, M)
            for j in range(1, 12):
                v = v0 + j * o
                mu, a = mu_a(m, v, M)
                if mu != mu0 or (a - a0) % M != (d * (v - v0)) % M:
                    bad_ab += 1
        if len({(d * o * j) % M for j in range(M)}) != M:
            bad_c += 1
    print("  %d (machine, odd M) pairs meeting the hypotheses" % tested)
    print("  mu_v constant and a_v - a_v0 = delta(v-v0) on the class: "
          "%d violations" % bad_ab)
    print("  delta*ord*Z = Z_M under the hypotheses: %d violations" % bad_c)
    bad_d = n_d = 0
    random.seed(9)
    for _ in range(400):
        t = (random.randint(1, 5), random.choice([-1, 1, 3, 5, 2]),
             random.randint(1, 5), random.randint(1, 5), random.randint(-3, 3))
        M = random.randrange(3, 62, 2)
        if gcd(t[3], M) != 1 or gcd(order(2, M), M) != 1:
            continue
        n_d += 1
        if len(full_image(Machine(*t), random.randrange(M), M,
                          order(2, M) * M + 4)) != M:
            bad_d += 1
    print("  end-to-end: image = Z_M in %d cases with M < 62, %d failures"
          % (n_d, bad_d))
    return bad_ab == 0 and bad_c == 0 and bad_d == 0


def step2_needle():
    print("\nSTEP 2 -- COROLLARY: no odd prime separates the Space Needle")
    print("-" * 72)
    needle = Machine(1, 3, 1, 1, 0)
    primes = [p for p in range(3, 4000)
              if all(p % d for d in range(2, int(p ** .5) + 1))]
    hyp = sum(1 for p in primes
              if gcd(order(2, p), p) != 1 or gcd(1, p) != 1)
    small = [p for p in primes if p < 200]
    bad = sum(1 for p in small
              if len(full_image(needle, 3 % p, p, order(2, p) * p + 4)) != p)
    print("  %d odd primes below 4000; hypotheses fail for %d" % (len(primes), hyp))
    print("  end-to-end on the %d primes below 200: %d failures"
          % (len(small), bad))
    print("  (ord_p(2) | p-1, so the second hypothesis is automatic for primes)")
    return hyp == 0 and bad == 0


def step3_falsifier():
    print("\nSTEP 3 -- FALSIFIER: every separating certificate must break a")
    print("          hypothesis, or T12 is false")
    print("-" * 72)
    dec = [r for r in ROWS if r["cong"]]
    ref = ev = gd = 0
    for r in dec:
        m, d = int(r["cong"]), int(r["delta"])
        if m % 2 == 0:
            ev += 1
        elif gcd(d, m) != 1 or gcd(order(2, m), m) != 1:
            gd += 1
        else:
            ref += 1
    print("  %d machines decided by a congruence" % len(dec))
    print("    modulus even (T12 silent):            %d" % ev)
    print("    odd but a gcd hypothesis fails:       %d" % gd)
    print("    WOULD REFUTE T12:                     %d" % ref)
    return ref == 0


def step4_criteria():
    print("\nSTEP 4 -- C4 AND C6: complete on (Z_m)^5, then on the census")
    print("-" * 72)
    bad = 0
    for m, pred, name in ((4, C4, "C4"), (6, C6, "C6")):
        mism = sep = 0
        for tup in product(range(m), repeat=m and 5):
            got = separates(Machine(*tup), m)
            sep += got
            mism += (got != pred(*tup))
        bad += mism
        print("  %s: all %d residue tuples mod %d -- %d separate, %d mismatches"
              % (name, m ** 5, m, sep, mism))
    for r in ROWS:
        t = tuple(int(r[k]) for k in ("alpha", "beta", "gamma", "delta", "eps"))
        r["_t"] = t
        r["_sep"] = {s: separates(Machine(*t), s) for s in range(2, 7)}
    print("  against the census, all %d machines:" % len(ROWS))
    for m, pred, name in ((3, T3, "T3"), (4, C4, "C4"), (6, C6, "C6")):
        pd = nd = dn = 0
        for r in ROWS:
            here = bool(r["cong"]) and int(r["cong"]) == m
            p = pred(*r["_t"]) and not any(r["_sep"][s] for s in range(2, m))
            pd += p and here
            nd += p and not here
            dn += here and not p
        bad += nd + dn
        print("    %s (m = %d): predicted and decided %3d, predicted not "
              "decided %d, decided not predicted %d" % (name, m, pd, nd, dn))
    return bad == 0


def step5_moduli():
    print("\nSTEP 5 -- THE DECIDING-MODULUS CENSUS (RESULTS.md omitted m = 7)")
    print("-" * 72)
    from collections import Counter
    c = Counter(int(r["cong"]) for r in ROWS if r["cong"])
    print("  " + ", ".join("%d (%d)" % (m, n) for m, n in sorted(c.items())))
    print("  machines whose smallest deciding modulus is 7: %s"
          % [r["_t"] for r in ROWS if r["cong"] and int(r["cong"]) == 7])
    return True


def main():
    r = [step1_saturation(), step2_needle(), step3_falsifier(),
         step4_criteria(), step5_moduli()]
    print("\n" + "=" * 72)
    if all(r):
        print("RESULT: T12 proved and its steps verified; no odd prime can ever")
        print("separate the Needle; C4 and C6 exact on (Z_m)^5 and on the census.")
    else:
        print("RESULT: FAILED -- do not update the reports")


if __name__ == "__main__":
    main()
