"""The sieve lemma is universal, and the mechanical program is COMPLETE.

Yesterday `leads.py` collapsed four census leads by noticing they shared the
modulus A_v = 2^(v+2) - 1, and derived S_v = 2 B_v (mod A_v) "for alpha = 2,
beta = -1".  That attribution was too modest.  The derivation never uses either
value.  This file states the lemma in its real generality, uses it to close the
two leads that were declared open, sweeps the whole odd-beta box for anything
else it reaches, and then proves that it reaches nothing else.

--------------------------------------------------------------------------
THE UNIVERSAL SIEVE LEMMA (proved).  Let beta be odd, so A_v is odd.  On
branch v the WS3 sieve forbids a halt unless Q0 * 2^e = P0 (mod A_v), where
P0/Q0 is the fixed point of the branch map x -> (A_v x + (2 B_v - A_v) 2^v) /
2^(v+1); that is P0 = (2 B_v - A_v) 2^v and Q0 = 2^(v+1) - A_v.  Multiplying by
a unit power of two is free, so write the condition as 2^e = S_v (mod A_v) with
S_v := 2 P0 Q0^{-1}.  Reduce both parts mod A_v -- the -A_v terms simply vanish:

    Q0 = 2^(v+1) - A_v = 2^(v+1)          (mod A_v)
    P0 = (2 B_v - A_v) 2^v = 2 B_v 2^v = B_v 2^(v+1)   (mod A_v)

    =>  P0 Q0^{-1} = B_v   =>   **S_v = 2 B_v  (mod A_v).**

No hypothesis on alpha or beta is used beyond A_v odd (needed for 2 to be
invertible) and the branch being expanding (or the sieve says nothing at all).
Equivalently, and this is the form worth remembering:

    branch v can immediately precede a halt  <=>  B_v is in <2> mod A_v,

the multiplicative group generated by 2.  Verified below on the whole odd-beta
box, every branch v = 0..80: 0 mismatches.

THE LINEAR COROLLARY (proved).  A_v = alpha 2^(v+1) + beta gives
alpha 2^(v+1) = -beta (mod A_v), so multiplying S_v = gamma 2^(v+1) + 2 delta v
+ 2 eps by alpha kills the exponential term outright:

    **alpha S_v = 2 alpha delta v + 2 alpha eps - beta gamma   (mod A_v)**

-- affine in v, for every machine in the family.  For alpha = 1 this IS S_v.
The exponential is not in the target; it is only in the modulus.

--------------------------------------------------------------------------
WHAT THE LEMMA DECIDES.  A power of two is a unit, so S_v = 0 forbids a branch
at once.  Otherwise the question is whether S_v lands in <2>, and that depends
entirely on how big <2> is:

  LISTABLE classes -- ord_{A_v}(2) grows linearly in v, so <2> is a short
  explicit list and a parity/size argument can exclude S_v from it outright.
  Four classes are listable: (2,-1) with ord = v+2 and <2> = {2^i};
  (1,1) with ord = 2(v+1) and (2,1) with ord = 2(v+2), both giving the signed
  list {+-2^i}; and (3,3), where 3 | A_v.

  THIN classes -- ord grows exponentially on average (e.g. (1,3):
  4, 3, 10, 18, 12, 66, 130, 36, ...), <2> is a large unstructured subgroup,
  and membership of S_v is an S-unit condition with no elementary handle.
  The Space Needle (1,3,1,1,0) lives here: A_v = 2^(v+1)+3 makes 2^(v+1) = -3,
  so <2> = {+-3^a 2^i} and the halting condition on branch v reads

      2v - 3  in  {+-3^a 2^i}   (mod 2^(v+1) + 3)

  -- a 2,3-S-unit membership question, which is exactly the frontier.

THE TEN MACHINES (labels T1..T11 -- T3 is the m = 3 congruence criterion,
not a machine).  Every all-branches-forbidden machine in the box, with the
closed form of S_v (an exact integer identity, asserted below) and the pattern
that finishes it.  T1-T6 were known; T7-T11 are new here.  Powers of two mod
A_v: for A_v = 2^(v+2)-1 they are exactly {1, 2, ..., 2^(v+1)}; for
A_v = 2^(v+2)+1 exactly {+-2^i : i <= v+1}.

 T1  (1, 1,2,0,1)   S_v = 0            B_v = A_v, so 2B_v = 2A_v = 0.  Pattern
                                       (iv): 0 is not a unit, powers are.
 T9  (2,-1,2,0,1)   S_v = 3            2B_v = A_v + 3 exactly.  Pattern (i):
                                       odd, 1 < 3 < A_v for v >= 1; v = 0 gives
                                       A_0 = 3 and S_0 = 0.
 T2  (2,-1,2,1,1)   S_v = 2v + 3       pattern (i), v >= 1; v = 0 gives 0.
 T4  (2,-1,2,2,1)   S_v = 4v + 3       pattern (i), v >= 2; v = 0,1 give 0.
 T5  (2,-1,3,0,0)   S_v = 2^(v+1)+1    pattern (i), v >= 1 since 2 < 2^(v+1);
                                       v = 0 gives 0.
 T6  (2,-1,3,1,0)   S_v = 2^(v+1)+2v+1 pattern (i), v >= 2 since 2v+2 <
                                       2^(v+1); v = 0,1 give 0.
 T10 (2,-1,1,2,-1)  S_v = 2^(v+1)+4v-2 pattern (ii): S_v = 2*(2^v + 2v - 1) is
                                       2*odd for v >= 1, and S_v < A_v since
                                       4v-1 < 2^(v+1); so S_v = 2^i forces
                                       i = 1, i.e. 2^v = 2 - 2v, impossible.
                                       v = 0 gives B_0 = 0, S_0 = 0.
 T7  (2, 1,1,2,-1)  S_v = 2^(v+1)+4v-2 same S_v, signed list mod 2^(v+2)+1.
                                       S_v = 2^i: as above, impossible.
                                       S_v = A_v - 2^i: S_v is even and A_v odd
                                       force i = 0, i.e. 4v - 2 = 2^(v+1),
                                       which never holds.  v = 0 gives S_0 = 0.
 T8  (3, 3,2,0,1)   S_v = 0 mod d_v    d_v := 2^(v+1)+1 divides A_v = 3 d_v,
                                       and B_v = d_v exactly, so S_v = 2 d_v.
                                       Pattern (iii): every power of two is a
                                       unit mod d_v >= 3, so none is 0 there.
 T11 (3, 3,3,0,0)   S_v = -3           2B_v = A_v - 3 exactly, and 3 | A_v, so
                                       S_v = 0 (mod 3).  Pattern (iii) with the
                                       fixed divisor 3: powers of two mod 3 are
                                       {1,2}, never 0.

Each is a proof that the machine NEVER HALTS AFTER ITS FIRST STEP -- the
powers of two are exactly its halting starts, and they halt at step 0.

THE COMPLETENESS THEOREM (this is the point of the file).  Those ten are all
there are.  For every other well-defined odd-beta machine in the census box the
sweep below returns an EXPLICIT SURVIVING BRANCH: a v <= 22 together with the
exponent e witnessing 2^e = S_v (mod A_v).  A surviving branch is a positive
certificate, not a failure to find one, so this is not exhaustion -- it is a
proof that the sieve-to-theorem pipeline is finished on this family.  What is
NOT claimed: a surviving branch does not make a machine halt.  It only means
this method cannot decide it, and something else must.

WHAT IS STILL ONLY MACHINE-VERIFIED: the lemma's domain (v <= 80 over the box)
and the completeness sweep's domain (v <= 22) are stated with every number the
run produced.  The ten machine theorems themselves are proved -- the closed forms
are exact integer identities, asserted here rather than fitted.
"""
import sys
from itertools import product
from math import isqrt

sys.path.insert(0, "/Users/tomzahavy/Documents/Claude/collatz/census")
from family import Machine
from decide import congruence_proof

LEMMA_VMAX = 80        # domain of the universal-lemma check
SWEEP_VMAX = 22        # domain of the completeness sweep (mass 1 - 2^-23)
DEEP_VMAX = 200        # deep re-check of the ten
ALPHAS, BETAS = (1, 2, 3), (-1, 1, 3, 5, 7)
GAMMAS, DELTAS, EPSS = (1, 2, 3), (0, 1, 2), (-2, -1, 0, 1, 2)

# S_v as an exact integer, DERIVED (see docstring); asserted, never fitted.
THEOREMS = {
    (1, 1, 2, 0, 1):  ("T1",  "0",                 lambda v: 0,                          "iv"),
    (2, -1, 2, 0, 1): ("T9",  "3",                 lambda v: 3,                          "i"),
    (2, -1, 2, 1, 1): ("T2",  "2v + 3",            lambda v: 2 * v + 3,                  "i"),
    (2, -1, 2, 2, 1): ("T4",  "4v + 3",            lambda v: 4 * v + 3,                  "i"),
    (2, -1, 3, 0, 0): ("T5",  "2^(v+1) + 1",       lambda v: (1 << (v + 1)) + 1,         "i"),
    (2, -1, 3, 1, 0): ("T6",  "2^(v+1) + 2v + 1",  lambda v: (1 << (v + 1)) + 2 * v + 1, "i"),
    (2, -1, 1, 2, -1): ("T10", "2^(v+1) + 4v - 2", lambda v: (1 << (v + 1)) + 4 * v - 2, "ii"),
    (2, 1, 1, 2, -1): ("T7",  "2^(v+1) + 4v - 2",  lambda v: (1 << (v + 1)) + 4 * v - 2, "ii"),
    (3, 3, 2, 0, 1):  ("T8",  "0 mod d_v",         lambda v: 2 * ((1 << (v + 1)) + 1),   "iii"),
    (3, 3, 3, 0, 0):  ("T11", "-3",                lambda v: -3,                         "iii"),
}


def machines():
    """Every well-defined odd-beta member of the census box."""
    out = []
    for t in product(ALPHAS, BETAS, GAMMAS, DELTAS, EPSS):
        m = Machine(*t)
        if m.well_defined():
            out.append((t, m))
    return out


def target(mach, v):
    """S_v from the sieve's own fixed-point data, or None if the sieve is silent."""
    data = mach.branch_sieve_data(v)
    if data is None:
        return None
    _, _, P, Q, _ = data
    A = mach.A(v)
    return (2 * (P * pow(Q, -1, A))) % A


def order_of_2(A):
    o, p = 1, 2 % A
    while p != 1:
        p, o = (p * 2) % A, o + 1
    return o


def pow2_witness(S, A, baby, M, giant):
    """The exponent e with 2^e = S (mod A), or None.  Baby table is shared
    across all machines of an (alpha,beta,v) class -- A depends only on those."""
    S %= A
    if S == 0:
        return None
    y = S
    for i in range(M + 1):
        j = baby.get(y)
        if j is not None:
            return i * M + j
        y = (y * giant) % A
    return None


def step1_lemma(box):
    print("STEP 1 -- THE UNIVERSAL LEMMA:  S_v = 2 B_v (mod A_v), beta odd")
    print("-" * 74)
    bad = tested = live = 0
    for _, m in box:
        seen = False
        for v in range(LEMMA_VMAX + 1):
            S = target(m, v)
            if S is None:
                continue
            seen = True
            tested += 1
            if S != (2 * m.B(v)) % m.A(v):
                bad += 1
        live += seen
    print("  %d machines (%d with a non-silent sieve), %d branches, v = 0..%d"
          % (len(box), live, tested, LEMMA_VMAX))
    print("  mismatches: %d  ->  %s\n"
          % (bad, "lemma holds" if bad == 0 else "LEMMA FALSE -- stop here"))
    return bad == 0


def step2_linear(box):
    print("STEP 2 -- THE LINEAR COROLLARY:  a S_v = 2 a d v + 2 a e - b g (mod A_v)")
    print("-" * 74)
    bad = tested = 0
    for (a, b, g, d, e), m in box:
        for v in range(LEMMA_VMAX + 1):
            S = target(m, v)
            if S is None:
                continue
            tested += 1
            if (a * S) % m.A(v) != (2 * a * d * v + 2 * a * e - b * g) % m.A(v):
                bad += 1
    print("  %d branches tested; mismatches: %d  ->  %s\n"
          % (tested, bad, "linear in v, every machine"
             if bad == 0 else "COROLLARY FALSE -- stop here"))
    return bad == 0


def step3_orders():
    """Classify each (alpha,beta) class by the size of <2> mod A_v.

    The silence test is EXPANSION, not the order computation: the sieve argues
    from a branch's affine fixed point, so a branch with A_v <= 2^(v+1) gives it
    nothing to say.  That is why the whole (1,-1) class is silent -- its orders
    are perfectly small, but no branch of it expands.
    """
    print("STEP 3 -- WHY SOME CLASSES ARE DECIDABLE BY HAND: the size of <2>")
    print("-" * 74)
    print("  %-9s %-26s %s" % ("(a,b)", "ord_{A_v}(2), v = 0..7", "kind"))
    kinds = {}
    for a, b in product(ALPHAS, BETAS):
        m = Machine(a, b, 1, 0, 0)
        ords = [order_of_2(m.A(v)) if m.A(v) > 1 and m.A(v) % 2 else None
                for v in range(8)]
        if all(m.branch_sieve_data(v) is None for v in range(SWEEP_VMAX + 1)):
            kind = "silent (no expanding branch)"
        elif all(o is not None and o <= 8 * (v + 2) for v, o in enumerate(ords)):
            kind = "LISTABLE"
        else:
            kind = "thin"
        kinds[(a, b)] = kind
        print("  %-9s %-26s %s"
              % ("(%d,%d)" % (a, b),
                 ",".join("-" if o is None else str(o) for o in ords), kind))
    print()
    return kinds


def baby_tables():
    """One shared BSGS table per (alpha,beta,v): A_v depends only on those."""
    tables = {}
    for a, b in product(ALPHAS, BETAS):
        mm = Machine(a, b, 1, 0, 0)
        for v in range(SWEEP_VMAX + 1):
            A = mm.A(v)
            if A < 3 or A % 2 == 0:
                continue
            M = isqrt(A) + 1
            baby, p = {}, 1 % A
            for j in range(M):
                baby.setdefault(p, j)
                p = (p * 2) % A
            tables[(a, b, v)] = (baby, M, pow(pow(2, M, A), -1, A))
    return tables


def step4_sweep(box, tables):
    """Every machine: forbidden mass, and an explicit surviving branch if any."""
    print("STEP 4 -- THE COMPLETENESS SWEEP (v <= %d, shared baby tables)" % SWEEP_VMAX)
    print("-" * 74)
    allforb, survivors, silent = [], {}, []
    for t, m in box:
        a, b = t[0], t[1]
        tested = forb = 0
        witness = None
        for v in range(SWEEP_VMAX + 1):
            S = target(m, v)
            if S is None:
                continue
            tested += 1
            baby, M, giant = tables[(a, b, v)]
            e = pow2_witness(S, m.A(v), baby, M, giant)
            if e is None:
                forb += 1
            elif witness is None:
                witness = (v, e, S, m.A(v))
        if tested == 0:
            silent.append(t)
        elif witness is None:
            allforb.append(t)
        else:
            survivors[t] = witness
    print("  machines swept: %d" % len(box))
    print("  sieve-silent (no expanding branch, sieve says nothing): %d" % len(silent))
    print("  with an EXPLICIT surviving branch (positive certificate): %d"
          % len(survivors))
    print("  with every branch forbidden: %d" % len(allforb))
    ok = True
    for t in allforb:
        if t not in THEOREMS:
            print("  *** UNCLAIMED all-forbidden machine %s -- investigate" % (t,))
            ok = False
    for t in THEOREMS:
        if t not in allforb:
            print("  *** claimed theorem %s has a surviving branch -- WRONG" % (t,))
            ok = False
    print("  matches the ten claimed machines exactly: %s" % ("yes" if ok else "NO"))
    ex = sorted(survivors)[0]
    v, e, S, A = survivors[ex]
    print("  sample certificate: %s survives at v = %d, 2^%d = %d (mod %d): %s"
          % (str(ex), v, e, S, A, pow(2, e, A) == S % A))
    print()
    return allforb, survivors, silent, ok


def step5_closed_forms(allforb):
    print("STEP 5 -- THE TEN MACHINES: closed forms asserted, every branch forbidden")
    print("-" * 74)
    print("  %-17s %-5s %-19s %-4s %s"
          % ("machine", "name", "S_v (derived)", "pat", "branches forbidden, v <= %d" % DEEP_VMAX))
    ok = True
    for t in sorted(THEOREMS, key=lambda k: int(THEOREMS[k][0][1:])):
        name, form, f, pat = THEOREMS[t]
        m = Machine(*t)
        mism = surv = tested = 0
        for v in range(DEEP_VMAX + 1):
            S = target(m, v)
            if S is None:
                continue
            tested += 1
            A = m.A(v)
            if S != f(v) % A:
                mism += 1
            pows, p = set(), 1 % A
            while p not in pows:            # orders here are O(v): cheap
                pows.add(p)
                p = (p * 2) % A
            if S in pows:
                surv += 1
        if mism or surv:
            ok = False
        print("  %-17s %-5s %-19s %-4s %s"
              % (str(t), name, form, pat,
                 "all %d forbidden" % tested if not surv
                 else "%d SURVIVE" % surv)
              + ("" if not mism else "   %d FORM ERRORS" % mism))
    print()
    return ok


def step6_brute(allforb):
    print("STEP 6 -- BRUTE FORCE: no orbit reaches a power of two after >= 1 step")
    print("-" * 74)
    print("  (starts that ARE powers of two halt at step 0 and are excluded)")
    total = 0
    for t in sorted(THEOREMS, key=lambda k: int(THEOREMS[k][0][1:])):
        m, bad = Machine(*t), 0
        for x0 in range(2, 20000):
            if x0 & (x0 - 1) == 0:
                continue
            x = x0
            for _ in range(400):
                y = m.step(x)
                if y == "HALT":
                    bad += 1
                    break
                if y.bit_length() > 6000:
                    break
                x = y
        total += bad
        print("  %-5s %-17s starts 2..19999, 400 steps: halts = %d"
              % (THEOREMS[t][0], str(t), bad))
    print("  total counterexamples: %d\n" % total)
    return total == 0


def step7_tiers(box, allforb, survivors, silent, kinds, tables):
    """Where the 636 undecided machines actually stand."""
    print("STEP 7 -- THE FRONTIER MAP (odd beta, not decided by congruence)")
    print("-" * 74)
    tiers = {"1 mechanical (proved)": [], "2 S-unit (thin, sieve bites)": [],
             "3a sieve-closed (listable, branch survives)": [],
             "3b sieve-void (thin, mass 0)": [], "3c sieve-silent": []}
    undecided = 0
    for t, m in box:
        if congruence_proof(m, 3) is not None:
            continue
        undecided += 1
        ab = (t[0], t[1])
        if t in allforb:
            tiers["1 mechanical (proved)"].append(t)
        elif t in silent:
            tiers["3c sieve-silent"].append(t)
        else:
            forb = tested = 0
            for v in range(SWEEP_VMAX + 1):
                S = target(m, v)
                if S is None:
                    continue
                tested += 1
                baby, M, giant = tables[(t[0], t[1], v)]
                if pow2_witness(S, m.A(v), baby, M, giant) is None:
                    forb += 1
            if kinds[ab] == "LISTABLE":
                tiers["3a sieve-closed (listable, branch survives)"].append(t)
            elif forb == 0:
                tiers["3b sieve-void (thin, mass 0)"].append(t)
            else:
                tiers["2 S-unit (thin, sieve bites)"].append(t)
    print("  odd-beta machines not decided by congruence: %d" % undecided)
    for k in sorted(tiers):
        print("    tier %-45s %4d" % (k, len(tiers[k])))
    needle = (1, 3, 1, 1, 0)
    print("  the Space Needle %s is in tier: %s"
          % (str(needle),
             next(k for k in tiers if needle in tiers[k])))
    fam = [t for t in tiers["2 S-unit (thin, sieve bites)"] if (t[0], t[1]) in
           ((1, 3), (2, 3), (3, 1))]
    print("  tier-2 members sharing the Needle's group <2,-3>: %d" % len(fam))
    print()
    return tiers


def step8_needle():
    print("STEP 8 -- THE NEEDLE'S CONDITION, AND WHY IT DOES NOT CLOSE")
    print("-" * 74)
    m = Machine(1, 3, 1, 1, 0)
    bad = 0
    for v in range(DEEP_VMAX + 1):
        S = target(m, v)
        if S is None:
            continue
        if S != (2 * v - 3) % m.A(v):
            bad += 1
    print("  closed form S_v = 2v - 3 (mod 2^(v+1)+3), v <= %d: %d mismatches"
          % (DEEP_VMAX, bad))
    forb, unforb, mass = [], [], 0.0
    for v in range(41):
        S = target(m, v)
        if S is None:
            continue
        A = m.A(v)
        M = isqrt(A) + 1
        baby, p = {}, 1 % A
        for j in range(M):
            baby.setdefault(p, j)
            p = (p * 2) % A
        if pow2_witness(S, A, baby, M, pow(pow(2, M, A), -1, A)) is None:
            forb.append(v)
            mass += 2.0 ** -(v + 1)
        else:
            unforb.append(v)
    print("  forbidden branches v <= 40: %d;  surviving: %d" % (len(forb), len(unforb)))
    print("  surviving branches: %s" % unforb)
    print("  weighted forbidden mass: %.4f   (WS3 measured 0.287 independently)"
          % mass)
    print("  forbidden among the first 35 valuations: %d   (WS3 reported 19)"
          % len([v for v in forb if v <= 34]))
    print("  -> the surviving set does NOT thin out: no asymptotic theorem here.")
    print()
    return bad == 0


def main():
    box = machines()
    r1 = step1_lemma(box)
    r2 = step2_linear(box)
    kinds = step3_orders()
    tables = baby_tables()
    allforb, survivors, silent, r4 = step4_sweep(box, tables)
    r5 = step5_closed_forms(allforb)
    r6 = step6_brute(allforb)
    step7_tiers(box, allforb, survivors, silent, kinds, tables)
    r8 = step8_needle()
    print("=" * 74)
    if all([r1, r2, r4, r5, r6, r8]):
        print("RESULT: the lemma is universal; T7-T11 join T1-T6; and the sweep")
        print("returns an explicit surviving branch for every other machine in")
        print("the box: the sieve-to-theorem pipeline is COMPLETE at ten machines.")
    else:
        print("RESULT: FAILED -- do not update the reports")


if __name__ == "__main__":
    main()
