import LeanBbf
#print axioms Fractran.M431.m431_never_halts
#print axioms Fractran.Siblings431.m673_never_halts
#print axioms Fractran.Siblings431.m502_never_halts
#print axioms Fractran.Siblings431.m623_never_halts
#print axioms Fractran.M455.m455_never_halts
#print axioms Fractran.M678.m678_never_halts
#print axioms Fractran.M574.m574_never_halts
#print axioms Fractran.M570.m570_never_halts
#print axioms Fractran.M680.m680_never_halts
#print axioms Fractran.Decider.neverHalts_of_phases
#print axioms Fractran.Decider.affine2_nonneg_of_corners
#print axioms Fractran.Decider.affine2_le_of_corners
#print axioms Fractran.Decider.single_conjunct_exclusion
#print axioms Fractran.Decider.disjunctive_endpoint_check_unsound
#print axioms Fractran.Decider.m574_via_certificate
#print axioms Fractran.Decider.m455_via_certificate
#print axioms Fractran.step_of_first
#print axioms Fractran.Exp.alwaysGE_sound
#print axioms Fractran.Exp.eval_mono
#print axioms Fractran.run_affine
#print axioms Fractran.run_affine_of_rule
#print axioms Fractran.coord_ge_of_endpoints
#print axioms Fractran.coord_lt_of_endpoints
